SELECT
  (SELECT CASE WHEN typeof(v) = 'real' THEN CAST(ROUND(v) AS INTEGER) ELSE CAST(v AS INTEGER) END FROM (SELECT (CAST(5 AS REAL) / NULLIF(2, 0)) AS v)) AS a,
  (SELECT CASE WHEN typeof(v) = 'real' THEN CAST(ROUND(v) AS INTEGER) ELSE CAST(v AS INTEGER) END FROM (SELECT - (CAST(5 AS REAL) / NULLIF(2, 0)) AS v)) AS b,
  (SELECT CASE WHEN typeof(v) = 'real' THEN CAST(ROUND(v) AS INTEGER) ELSE CAST(v AS INTEGER) END FROM (SELECT 3.7 AS v)) AS c,
  (SELECT CASE WHEN typeof(v) = 'real' THEN CAST(ROUND(v) AS INTEGER) ELSE CAST(v AS INTEGER) END FROM (SELECT (CAST(9 AS REAL) / NULLIF(4, 0)) AS v)) AS d;