WITH t_0_V AS (SELECT * FROM (
  
    SELECT
      1 AS k
   UNION ALL
  
    SELECT
      2 AS k
  
) AS UNUSED_TABLE_NAME  )
SELECT
  V.k AS k,
  JSON_ARRAY_LENGTH(CASE WHEN (V.k = 1) THEN JSON_ARRAY() ELSE JSON_ARRAY('a', 'b') END) AS n
FROM
  t_0_V AS V ORDER BY k;