WITH t_0_V AS (SELECT * FROM (
  
    SELECT
      1 AS k
   UNION ALL
  
    SELECT
      2 AS k
  
) AS UNUSED_TABLE_NAME  )
SELECT
  V.k AS k,
  (CASE WHEN CASE WHEN (V.k = 1) THEN JSON_ARRAY() ELSE JSON_ARRAY('a', 'b') END IS NULL OR ',' IS NULL THEN NULL ELSE COALESCE((SELECT GROUP_CONCAT(value, ',') FROM (SELECT value FROM JSON_EACH(CASE WHEN (V.k = 1) THEN JSON_ARRAY() ELSE JSON_ARRAY('a', 'b') END) WHERE value IS NOT NULL ORDER BY key)), '') END) AS s
FROM
  t_0_V AS V ORDER BY k NULLS LAST;