SELECT
  JSON_ARRAY_LENGTH(SPLIT('a,,b', ',')) AS n,
  (CASE WHEN SPLIT('a,,b', ',') IS NULL OR ',' IS NULL THEN NULL ELSE COALESCE((SELECT GROUP_CONCAT(value, ',') FROM (SELECT value FROM JSON_EACH(SPLIT('a,,b', ',')) WHERE value IS NOT NULL ORDER BY key)), '') END) AS s;