SELECT
  JSON_ARRAY_LENGTH(SPLIT(',a,', ',')) AS n,
  (CASE WHEN SPLIT(',a,', ',') IS NULL OR ',' IS NULL THEN NULL ELSE COALESCE((SELECT GROUP_CONCAT(value, ',') FROM (SELECT value FROM JSON_EACH(SPLIT(',a,', ',')) WHERE value IS NOT NULL ORDER BY key)), '') END) AS s;