SELECT
  JSON_ARRAY_LENGTH(SPLIT('x', ',')) AS n,
  (CASE WHEN SPLIT('x', ',') IS NULL OR ',' IS NULL THEN NULL ELSE COALESCE((SELECT GROUP_CONCAT(value, ',') FROM (SELECT value FROM JSON_EACH(SPLIT('x', ',')) WHERE value IS NOT NULL ORDER BY key)), '') END) AS s;