SELECT
  (((((((SELECT CASE WHEN typeof(v) = 'real' THEN CAST(ROUND(v) AS INTEGER) ELSE CAST(v AS INTEGER) END FROM (SELECT 1024 AS v))) * (1024))) * (1024))) * (1024)) AS v,
  (((SELECT CASE WHEN typeof(v) = 'real' THEN CAST(ROUND(v) AS INTEGER) ELSE CAST(v AS INTEGER) END FROM (SELECT 2147483647 AS v))) + (1)) AS w;