SELECT
  CASE WHEN (5 < 10) THEN (('0') || (SYNALOG_NUMBER_TEXT(5))) ELSE SYNALOG_NUMBER_TEXT(5) END AS a,
  CASE WHEN (12 < 10) THEN (('0') || (SYNALOG_NUMBER_TEXT(12))) ELSE SYNALOG_NUMBER_TEXT(12) END AS b;