SELECT
  (SELECT CASE WHEN typeof(v) = 'real' THEN CAST(ROUND(v) AS INTEGER) ELSE CAST(v AS INTEGER) END FROM (SELECT SUBSTR(x_2.value, 9, 2) AS v)) AS day
FROM
  JSON_EACH(JSON_ARRAY('2024-01-31', '2024-02-01')) as x_2 ORDER BY day NULLS LAST;