WITH t_0_C AS (SELECT
  (CASE WHEN COUNT(*) = 0 THEN NULL ELSE JSON_GROUP_ARRAY(x_3.value) END) AS l
FROM
  JSON_EACH(JSON_ARRAY(1)) as x_3
WHERE
  (x_3.value > 5))
SELECT
  COALESCE(JSON_ARRAY_LENGTH(C.l), 0) AS n
FROM
  t_0_C AS C;