SELECT
  SUM((((SELECT CASE WHEN typeof(v) = 'real' THEN CAST(ROUND(v) AS INTEGER) ELSE CAST(v AS INTEGER) END FROM (SELECT x_2.value AS v))) * (1000000000))) AS t
FROM
  JSON_EACH(JSON_ARRAY(1, 2, 3)) as x_2;