#!/usr/bin/env python3
"""Generate expected SQL golden files for compiler tests using Python Logica.

Layout: canonical engine-independent sources live in fixtures/*.l; each
engine directory holds the golden .sql files plus optional .l overrides for
programs that genuinely differ on that engine (and engine-only fixtures).

For each fixture, compiles the last user-defined predicate with the target
engine and writes the SQL to <engine>/<test_name>.sql.

Fixtures listed in SYNALOG_GOLDENS or ABSENT_GOLDENS (see DEVIATIONS.md) are
never overwritten by this script:
  - SYNALOG_GOLDENS deviate from upstream on purpose; regenerate them with
    `synalog.compile` instead.
  - ABSENT_GOLDENS document compiler subsystems synalog does not have yet.

Usage:
    python3 generate_expected_sql.py

Requires the logica package (GitHub main, see DEVIATIONS.md / project notes):
    pip install logica
"""

import glob
import os
import signal
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Set up import path for Logica imports BEFORE importing logica
os.environ['LOGICAPATH'] = SCRIPT_DIR
os.chdir(SCRIPT_DIR)

from logica.parser_py import parse as logica_parse
from logica.compiler import universe

ENGINES = ["sqlite", "duckdb", "psql", "bigquery", "trino", "presto", "databricks"]

# Goldens intentionally generated from synalog, not upstream (DEVIATIONS.md).
SYNALOG_GOLDENS = {
    ("trino", "06_arrays"), ("trino", "23_combine"), ("trino", "48_split_function"),
    ("trino", "50_array_functions"), ("trino", "51_math_functions"),
    ("presto", "06_arrays"), ("presto", "23_combine"), ("presto", "48_split_function"),
    ("presto", "50_array_functions"), ("presto", "51_math_functions"),
    # PrestoDB has no FORMAT/printf; synalog lowers Format(...) to a `||` concat
    # chain (see DEVIATIONS.md). Trino keeps the native FORMAT.
    ("presto", "56_format"),
    ("psql", "23_combine"),
    # DuckDB recursion: upstream routes DuckDB to the iterative flat path, which
    # needs a runtime fixpoint loop and truncates the closure under synalog's
    # static single-script compilation. synalog uses the inline unrolling (like
    # every other engine), which is correct; see DEVIATIONS.md.
    ("duckdb", "35_recursive_annotated"),
    # DuckDB `LOG(x)` is base-10; Logica's `Log` is natural log, so synalog emits
    # `LN(x)` (upstream's `LOG` is numerically wrong here). Same fix as trino/presto.
    ("duckdb", "51_math_functions"),
    # When one base table feeds multiple @Ground predicates, upstream globally
    # numbers its alias (t_1_Sales, t_2_Sales) while synalog aliases each as the
    # predicate name (Sales). Cosmetic only — both are valid and produce identical
    # results on every engine (verified in tests/e2e); see DEVIATIONS.md.
    *(((e, "62_multi_ground_join") for e in
       ["bigquery", "sqlite", "psql", "duckdb", "trino", "presto", "databricks"])),
    # Today/Now are synalog-only built-in temporal concepts: the compiler inlines
    # a per-dialect one-row relation (native current date/timestamp). Upstream
    # Logica has no such concept, so these goldens come from synalog on every
    # engine (see DEVIATIONS.md).
    *(("sqlite", "52_today_now"), ("duckdb", "52_today_now"), ("psql", "52_today_now"),
      ("bigquery", "52_today_now"), ("trino", "52_today_now"), ("presto", "52_today_now"),
      ("databricks", "52_today_now")),
    # A predicate named after an SQL keyword (`Values`, `Rows`): upstream uses
    # the name as a bare table alias (`t_1_Values AS Values`), which no engine
    # parses; synalog falls back to its numbered alias. See DEVIATIONS.md.
    *(((e, f) for e in ["bigquery", "sqlite", "psql", "duckdb", "trino", "presto", "databricks"]
       for f in ["44_import_extend", "48_split_function"])),
    # Databricks: synalog emits Spark/Databricks-valid SQL where upstream Logica
    # emits BigQuery-isms that do not run on Databricks (GENERATE_ARRAY,
    # ARRAY_LENGTH, FORMAT, OFFSET, in-aggregate ARRAY_AGG ORDER BY, ARRAY_JOIN
    # for concat, `::` casts). Verified against Apache Spark; see DEVIATIONS.md.
    # A functor applied to an imported predicate: upstream Logica leaves the
    # argument unresolved (the module prefixed its predicates), so the functor
    # silently returns the generic rule's rows. synalog resolves it; see
    # DEVIATIONS.md.
    *(((e, "63_functor_imported") for e in
       ["bigquery", "sqlite", "psql", "duckdb", "trino", "presto", "databricks"])),
    *(("databricks", n) for n in [
        "02_arithmetic", "03_comparison", "04_logical_operators", "06_arrays",
        "08_aggregations_array", "09_argmin_argmax", "10_negation",
        "11_disjunction", "12_if_then_else", "15_annotations", "19_type_casting",
        "20_list_comprehension", "22_multi_predicate", "23_combine",
        "25_inline_annotations", "26_builtin_functions", "27_assignment",
        "27_boolean_ops", "28_multi_rule_predicate", "29_argmin_argmax",
        "30_complex_expressions", "31_user_functions", "33_string_manipulation",
        "36_range_operations", "41_edge_arithmetic", "46_constraint",
        "47_like_pattern", "48_split_function", "50_array_functions",
        "54_sqlexpr", "55_argmax_k", "56_format",
    ]),
    # 17_outer_join tests `Test` (its ContactInfo concatenates arrays: no
    # ARRAY_CONCAT_AGG outside BigQuery; psql's empty arrays are '{}').
    ("trino", "17_outer_join"), ("presto", "17_outer_join"),
    ("databricks", "17_outer_join"), ("psql", "17_outer_join"),
    # Records are ROW casts on Presto/Trino and declared types on psql;
    # psql's natural logarithm is LN (see DEVIATIONS.md).
    ("trino", "32_nested_records"), ("presto", "32_nested_records"), ("psql", "32_nested_records"),
    ("psql", "51_math_functions"),
    # Columns named after SQL keywords are quoted, deep recursion is written
    # out as a script (see DEVIATIONS.md).
    *{(engine, "64_keyword_columns") for engine in ("bigquery", "databricks", "duckdb", "presto", "psql", "sqlite", "trino")},
    *{(engine, "65_deep_recursion") for engine in ("bigquery", "databricks", "duckdb", "presto", "psql", "sqlite", "trino")},
    *{(engine, "66_deep_mutual_recursion") for engine in ("bigquery", "databricks", "duckdb", "presto", "psql", "sqlite", "trino")},
    # Fixtures from tests/programs (see DEVIATIONS.md for each reason).
    # A keyword inside an underscored name: upstream splits the rule.
    ("bigquery", "108_execution_keyword_inside_a_name"),
    ("bigquery", "209_verifier_keyword_in_an_underscored_name"),
    ("databricks", "108_execution_keyword_inside_a_name"),
    ("databricks", "209_verifier_keyword_in_an_underscored_name"),
    ("duckdb", "108_execution_keyword_inside_a_name"),
    ("duckdb", "209_verifier_keyword_in_an_underscored_name"),
    ("presto", "108_execution_keyword_inside_a_name"),
    ("presto", "209_verifier_keyword_in_an_underscored_name"),
    ("psql", "108_execution_keyword_inside_a_name"),
    ("psql", "209_verifier_keyword_in_an_underscored_name"),
    ("sqlite", "108_execution_keyword_inside_a_name"),
    ("sqlite", "209_verifier_keyword_in_an_underscored_name"),
    ("trino", "108_execution_keyword_inside_a_name"),
    ("trino", "209_verifier_keyword_in_an_underscored_name"),
    # Deep recursion written out as a script.
    ("bigquery", "148_execution_deep_recursion"),
    ("bigquery", "158_execution_deep_recursion_odd_depth"),
    ("bigquery", "159_execution_deep_recursion_converges"),
    ("bigquery", "160_execution_deep_mutual_recursion"),
    ("bigquery", "183_keywords_keyword_column_in_deep_recursion"),
    ("bigquery", "189_recursion_depth_21_iterated"),
    ("bigquery", "190_recursion_depth_22"),
    ("bigquery", "191_recursion_depth_25"),
    ("bigquery", "194_recursion_deep_closure_with_pairs"),
    ("bigquery", "195_recursion_deep_recursion_used_twice"),
    ("bigquery", "196_recursion_two_deep_recursions"),
    ("bigquery", "197_recursion_deep_recursion_with_negation_after"),
    ("bigquery", "198_recursion_deep_shortest_path"),
    ("bigquery", "199_recursion_cycle_terminates"),
    ("bigquery", "65_deep_recursion"),
    ("bigquery", "66_deep_mutual_recursion"),
    ("databricks", "148_execution_deep_recursion"),
    ("databricks", "158_execution_deep_recursion_odd_depth"),
    ("databricks", "159_execution_deep_recursion_converges"),
    ("databricks", "160_execution_deep_mutual_recursion"),
    ("databricks", "183_keywords_keyword_column_in_deep_recursion"),
    ("databricks", "189_recursion_depth_21_iterated"),
    ("databricks", "190_recursion_depth_22"),
    ("databricks", "191_recursion_depth_25"),
    ("databricks", "194_recursion_deep_closure_with_pairs"),
    ("databricks", "195_recursion_deep_recursion_used_twice"),
    ("databricks", "196_recursion_two_deep_recursions"),
    ("databricks", "197_recursion_deep_recursion_with_negation_after"),
    ("databricks", "198_recursion_deep_shortest_path"),
    ("databricks", "199_recursion_cycle_terminates"),
    ("databricks", "65_deep_recursion"),
    ("databricks", "66_deep_mutual_recursion"),
    ("duckdb", "115_execution_recursion_depth_bounds"),
    ("duckdb", "148_execution_deep_recursion"),
    ("duckdb", "158_execution_deep_recursion_odd_depth"),
    ("duckdb", "159_execution_deep_recursion_converges"),
    ("duckdb", "160_execution_deep_mutual_recursion"),
    ("duckdb", "183_keywords_keyword_column_in_deep_recursion"),
    ("duckdb", "189_recursion_depth_21_iterated"),
    ("duckdb", "190_recursion_depth_22"),
    ("duckdb", "191_recursion_depth_25"),
    ("duckdb", "194_recursion_deep_closure_with_pairs"),
    ("duckdb", "195_recursion_deep_recursion_used_twice"),
    ("duckdb", "196_recursion_two_deep_recursions"),
    ("duckdb", "197_recursion_deep_recursion_with_negation_after"),
    ("duckdb", "198_recursion_deep_shortest_path"),
    ("duckdb", "199_recursion_cycle_terminates"),
    ("duckdb", "65_deep_recursion"),
    ("duckdb", "66_deep_mutual_recursion"),
    ("presto", "148_execution_deep_recursion"),
    ("presto", "158_execution_deep_recursion_odd_depth"),
    ("presto", "159_execution_deep_recursion_converges"),
    ("presto", "160_execution_deep_mutual_recursion"),
    ("presto", "183_keywords_keyword_column_in_deep_recursion"),
    ("presto", "189_recursion_depth_21_iterated"),
    ("presto", "190_recursion_depth_22"),
    ("presto", "191_recursion_depth_25"),
    ("presto", "194_recursion_deep_closure_with_pairs"),
    ("presto", "195_recursion_deep_recursion_used_twice"),
    ("presto", "196_recursion_two_deep_recursions"),
    ("presto", "197_recursion_deep_recursion_with_negation_after"),
    ("presto", "198_recursion_deep_shortest_path"),
    ("presto", "199_recursion_cycle_terminates"),
    ("presto", "65_deep_recursion"),
    ("presto", "66_deep_mutual_recursion"),
    ("psql", "148_execution_deep_recursion"),
    ("psql", "158_execution_deep_recursion_odd_depth"),
    ("psql", "159_execution_deep_recursion_converges"),
    ("psql", "160_execution_deep_mutual_recursion"),
    ("psql", "183_keywords_keyword_column_in_deep_recursion"),
    ("psql", "189_recursion_depth_21_iterated"),
    ("psql", "190_recursion_depth_22"),
    ("psql", "191_recursion_depth_25"),
    ("psql", "194_recursion_deep_closure_with_pairs"),
    ("psql", "195_recursion_deep_recursion_used_twice"),
    ("psql", "196_recursion_two_deep_recursions"),
    ("psql", "197_recursion_deep_recursion_with_negation_after"),
    ("psql", "198_recursion_deep_shortest_path"),
    ("psql", "199_recursion_cycle_terminates"),
    ("psql", "65_deep_recursion"),
    ("psql", "66_deep_mutual_recursion"),
    ("sqlite", "148_execution_deep_recursion"),
    ("sqlite", "158_execution_deep_recursion_odd_depth"),
    ("sqlite", "159_execution_deep_recursion_converges"),
    ("sqlite", "160_execution_deep_mutual_recursion"),
    ("sqlite", "183_keywords_keyword_column_in_deep_recursion"),
    ("sqlite", "189_recursion_depth_21_iterated"),
    ("sqlite", "190_recursion_depth_22"),
    ("sqlite", "191_recursion_depth_25"),
    ("sqlite", "194_recursion_deep_closure_with_pairs"),
    ("sqlite", "195_recursion_deep_recursion_used_twice"),
    ("sqlite", "196_recursion_two_deep_recursions"),
    ("sqlite", "197_recursion_deep_recursion_with_negation_after"),
    ("sqlite", "198_recursion_deep_shortest_path"),
    ("sqlite", "199_recursion_cycle_terminates"),
    ("sqlite", "65_deep_recursion"),
    ("sqlite", "66_deep_mutual_recursion"),
    ("trino", "148_execution_deep_recursion"),
    ("trino", "158_execution_deep_recursion_odd_depth"),
    ("trino", "159_execution_deep_recursion_converges"),
    ("trino", "160_execution_deep_mutual_recursion"),
    ("trino", "183_keywords_keyword_column_in_deep_recursion"),
    ("trino", "189_recursion_depth_21_iterated"),
    ("trino", "190_recursion_depth_22"),
    ("trino", "191_recursion_depth_25"),
    ("trino", "194_recursion_deep_closure_with_pairs"),
    ("trino", "195_recursion_deep_recursion_used_twice"),
    ("trino", "196_recursion_two_deep_recursions"),
    ("trino", "197_recursion_deep_recursion_with_negation_after"),
    ("trino", "198_recursion_deep_shortest_path"),
    ("trino", "199_recursion_cycle_terminates"),
    ("trino", "65_deep_recursion"),
    ("trino", "66_deep_mutual_recursion"),
    # Databricks: Spark SQL constructs.
    ("databricks", "102_execution_argmax"),
    ("databricks", "109_execution_string_functions"),
    ("databricks", "123_execution_like"),
    ("databricks", "132_execution_argmin"),
    ("databricks", "149_execution_range"),
    ("databricks", "188_recursion_depth_20_unrolled"),
    ("databricks", "99_execution_in_list"),
    # DuckDB recursion unrolled horizontally.
    ("duckdb", "105_execution_shortest_path"),
    ("duckdb", "114_execution_negation_of_derived"),
    ("duckdb", "138_execution_recursive_count"),
    ("duckdb", "139_execution_mutual_recursion"),
    ("duckdb", "187_recursion_depth_bounds_hops"),
    ("duckdb", "188_recursion_depth_20_unrolled"),
    ("duckdb", "200_recursion_depth_one"),
    ("duckdb", "202_verifier_recursion_with_depth"),
    ("duckdb", "92_execution_transitive_closure"),
    # Predicates and columns named after SQL keywords.
    ("bigquery", "155_execution_recursion_keyword_name"),
    ("bigquery", "156_execution_column_named_like_keyword"),
    ("bigquery", "161_execution_table_column_named_like_keyword"),
    ("bigquery", "174_keywords_column_order_in_join"),
    ("bigquery", "175_keywords_column_group_in_aggregate"),
    ("bigquery", "176_keywords_column_select_in_negation"),
    ("bigquery", "177_keywords_column_from_compared"),
    ("bigquery", "178_keywords_columns_where_and_limit"),
    ("bigquery", "179_keywords_keyword_column_in_order_by_desc"),
    ("bigquery", "180_keywords_keyword_column_paged"),
    ("bigquery", "181_keywords_keyword_column_searched"),
    ("bigquery", "182_keywords_keyword_column_in_recursion"),
    ("bigquery", "185_keywords_keyword_column_argmax"),
    ("bigquery", "186_keywords_mixed_case_keyword_column"),
    ("bigquery", "64_keyword_columns"),
    ("databricks", "155_execution_recursion_keyword_name"),
    ("databricks", "156_execution_column_named_like_keyword"),
    ("databricks", "161_execution_table_column_named_like_keyword"),
    ("databricks", "174_keywords_column_order_in_join"),
    ("databricks", "175_keywords_column_group_in_aggregate"),
    ("databricks", "176_keywords_column_select_in_negation"),
    ("databricks", "177_keywords_column_from_compared"),
    ("databricks", "178_keywords_columns_where_and_limit"),
    ("databricks", "179_keywords_keyword_column_in_order_by_desc"),
    ("databricks", "180_keywords_keyword_column_paged"),
    ("databricks", "181_keywords_keyword_column_searched"),
    ("databricks", "182_keywords_keyword_column_in_recursion"),
    ("databricks", "185_keywords_keyword_column_argmax"),
    ("databricks", "186_keywords_mixed_case_keyword_column"),
    ("databricks", "64_keyword_columns"),
    ("duckdb", "155_execution_recursion_keyword_name"),
    ("duckdb", "156_execution_column_named_like_keyword"),
    ("duckdb", "161_execution_table_column_named_like_keyword"),
    ("duckdb", "174_keywords_column_order_in_join"),
    ("duckdb", "175_keywords_column_group_in_aggregate"),
    ("duckdb", "176_keywords_column_select_in_negation"),
    ("duckdb", "177_keywords_column_from_compared"),
    ("duckdb", "178_keywords_columns_where_and_limit"),
    ("duckdb", "179_keywords_keyword_column_in_order_by_desc"),
    ("duckdb", "180_keywords_keyword_column_paged"),
    ("duckdb", "181_keywords_keyword_column_searched"),
    ("duckdb", "182_keywords_keyword_column_in_recursion"),
    ("duckdb", "184_keywords_keyword_column_functor"),
    ("duckdb", "185_keywords_keyword_column_argmax"),
    ("duckdb", "186_keywords_mixed_case_keyword_column"),
    ("duckdb", "64_keyword_columns"),
    ("presto", "155_execution_recursion_keyword_name"),
    ("presto", "156_execution_column_named_like_keyword"),
    ("presto", "161_execution_table_column_named_like_keyword"),
    ("presto", "174_keywords_column_order_in_join"),
    ("presto", "175_keywords_column_group_in_aggregate"),
    ("presto", "176_keywords_column_select_in_negation"),
    ("presto", "177_keywords_column_from_compared"),
    ("presto", "178_keywords_columns_where_and_limit"),
    ("presto", "179_keywords_keyword_column_in_order_by_desc"),
    ("presto", "180_keywords_keyword_column_paged"),
    ("presto", "181_keywords_keyword_column_searched"),
    ("presto", "182_keywords_keyword_column_in_recursion"),
    ("presto", "185_keywords_keyword_column_argmax"),
    ("presto", "186_keywords_mixed_case_keyword_column"),
    ("presto", "64_keyword_columns"),
    ("psql", "155_execution_recursion_keyword_name"),
    ("psql", "156_execution_column_named_like_keyword"),
    ("psql", "161_execution_table_column_named_like_keyword"),
    ("psql", "174_keywords_column_order_in_join"),
    ("psql", "175_keywords_column_group_in_aggregate"),
    ("psql", "176_keywords_column_select_in_negation"),
    ("psql", "177_keywords_column_from_compared"),
    ("psql", "178_keywords_columns_where_and_limit"),
    ("psql", "179_keywords_keyword_column_in_order_by_desc"),
    ("psql", "180_keywords_keyword_column_paged"),
    ("psql", "181_keywords_keyword_column_searched"),
    ("psql", "182_keywords_keyword_column_in_recursion"),
    ("psql", "184_keywords_keyword_column_functor"),
    ("psql", "185_keywords_keyword_column_argmax"),
    ("psql", "186_keywords_mixed_case_keyword_column"),
    ("psql", "64_keyword_columns"),
    ("sqlite", "155_execution_recursion_keyword_name"),
    ("sqlite", "156_execution_column_named_like_keyword"),
    ("sqlite", "161_execution_table_column_named_like_keyword"),
    ("sqlite", "174_keywords_column_order_in_join"),
    ("sqlite", "175_keywords_column_group_in_aggregate"),
    ("sqlite", "176_keywords_column_select_in_negation"),
    ("sqlite", "177_keywords_column_from_compared"),
    ("sqlite", "178_keywords_columns_where_and_limit"),
    ("sqlite", "179_keywords_keyword_column_in_order_by_desc"),
    ("sqlite", "180_keywords_keyword_column_paged"),
    ("sqlite", "181_keywords_keyword_column_searched"),
    ("sqlite", "182_keywords_keyword_column_in_recursion"),
    ("sqlite", "185_keywords_keyword_column_argmax"),
    ("sqlite", "186_keywords_mixed_case_keyword_column"),
    ("sqlite", "64_keyword_columns"),
    ("trino", "155_execution_recursion_keyword_name"),
    ("trino", "156_execution_column_named_like_keyword"),
    ("trino", "161_execution_table_column_named_like_keyword"),
    ("trino", "174_keywords_column_order_in_join"),
    ("trino", "175_keywords_column_group_in_aggregate"),
    ("trino", "176_keywords_column_select_in_negation"),
    ("trino", "177_keywords_column_from_compared"),
    ("trino", "178_keywords_columns_where_and_limit"),
    ("trino", "179_keywords_keyword_column_in_order_by_desc"),
    ("trino", "180_keywords_keyword_column_paged"),
    ("trino", "181_keywords_keyword_column_searched"),
    ("trino", "182_keywords_keyword_column_in_recursion"),
    ("trino", "185_keywords_keyword_column_argmax"),
    ("trino", "186_keywords_mixed_case_keyword_column"),
    ("trino", "64_keyword_columns"),
    # Front matter: upstream has none.
    ("bigquery", "163_front_matter_name_description_and_order"),
    ("bigquery", "164_front_matter_helpers_need_no_order"),
    ("bigquery", "165_front_matter_functor_result_named"),
    ("bigquery", "167_front_matter_extra_keys_are_the_hosts"),
    ("bigquery", "168_front_matter_quoted_colon_in_description"),
    ("bigquery", "169_front_matter_crlf_line_endings"),
    ("bigquery", "170_front_matter_multiline_description"),
    ("bigquery", "171_front_matter_dashes_in_a_string"),
    ("bigquery", "172_front_matter_name_with_spaces"),
    ("databricks", "163_front_matter_name_description_and_order"),
    ("databricks", "164_front_matter_helpers_need_no_order"),
    ("databricks", "165_front_matter_functor_result_named"),
    ("databricks", "167_front_matter_extra_keys_are_the_hosts"),
    ("databricks", "168_front_matter_quoted_colon_in_description"),
    ("databricks", "169_front_matter_crlf_line_endings"),
    ("databricks", "170_front_matter_multiline_description"),
    ("databricks", "171_front_matter_dashes_in_a_string"),
    ("databricks", "172_front_matter_name_with_spaces"),
    ("duckdb", "163_front_matter_name_description_and_order"),
    ("duckdb", "164_front_matter_helpers_need_no_order"),
    ("duckdb", "165_front_matter_functor_result_named"),
    ("duckdb", "167_front_matter_extra_keys_are_the_hosts"),
    ("duckdb", "168_front_matter_quoted_colon_in_description"),
    ("duckdb", "169_front_matter_crlf_line_endings"),
    ("duckdb", "170_front_matter_multiline_description"),
    ("duckdb", "171_front_matter_dashes_in_a_string"),
    ("duckdb", "172_front_matter_name_with_spaces"),
    ("presto", "163_front_matter_name_description_and_order"),
    ("presto", "164_front_matter_helpers_need_no_order"),
    ("presto", "165_front_matter_functor_result_named"),
    ("presto", "167_front_matter_extra_keys_are_the_hosts"),
    ("presto", "168_front_matter_quoted_colon_in_description"),
    ("presto", "169_front_matter_crlf_line_endings"),
    ("presto", "170_front_matter_multiline_description"),
    ("presto", "171_front_matter_dashes_in_a_string"),
    ("presto", "172_front_matter_name_with_spaces"),
    ("psql", "163_front_matter_name_description_and_order"),
    ("psql", "164_front_matter_helpers_need_no_order"),
    ("psql", "165_front_matter_functor_result_named"),
    ("psql", "167_front_matter_extra_keys_are_the_hosts"),
    ("psql", "168_front_matter_quoted_colon_in_description"),
    ("psql", "169_front_matter_crlf_line_endings"),
    ("psql", "170_front_matter_multiline_description"),
    ("psql", "171_front_matter_dashes_in_a_string"),
    ("psql", "172_front_matter_name_with_spaces"),
    ("sqlite", "163_front_matter_name_description_and_order"),
    ("sqlite", "164_front_matter_helpers_need_no_order"),
    ("sqlite", "165_front_matter_functor_result_named"),
    ("sqlite", "167_front_matter_extra_keys_are_the_hosts"),
    ("sqlite", "168_front_matter_quoted_colon_in_description"),
    ("sqlite", "169_front_matter_crlf_line_endings"),
    ("sqlite", "170_front_matter_multiline_description"),
    ("sqlite", "171_front_matter_dashes_in_a_string"),
    ("sqlite", "172_front_matter_name_with_spaces"),
    ("trino", "163_front_matter_name_description_and_order"),
    ("trino", "164_front_matter_helpers_need_no_order"),
    ("trino", "165_front_matter_functor_result_named"),
    ("trino", "167_front_matter_extra_keys_are_the_hosts"),
    ("trino", "168_front_matter_quoted_colon_in_description"),
    ("trino", "169_front_matter_crlf_line_endings"),
    ("trino", "170_front_matter_multiline_description"),
    ("trino", "171_front_matter_dashes_in_a_string"),
    ("trino", "172_front_matter_name_with_spaces"),
    # @Assert: upstream has none (it does not change the SQL).
    ("bigquery", "67_assertions_pending_before_its_predicate"),
    ("bigquery", "68_assertions_unbound_variable_is_unsupported"),
    ("bigquery", "69_assertions_assertion_on_limited_predicate"),
    ("bigquery", "70_assertions_pending_on_missing_helper"),
    ("bigquery", "71_assertions_assertion_reads_a_value_function"),
    ("databricks", "67_assertions_pending_before_its_predicate"),
    ("databricks", "68_assertions_unbound_variable_is_unsupported"),
    ("databricks", "69_assertions_assertion_on_limited_predicate"),
    ("databricks", "70_assertions_pending_on_missing_helper"),
    ("databricks", "71_assertions_assertion_reads_a_value_function"),
    ("duckdb", "67_assertions_pending_before_its_predicate"),
    ("duckdb", "68_assertions_unbound_variable_is_unsupported"),
    ("duckdb", "69_assertions_assertion_on_limited_predicate"),
    ("duckdb", "70_assertions_pending_on_missing_helper"),
    ("duckdb", "71_assertions_assertion_reads_a_value_function"),
    ("presto", "67_assertions_pending_before_its_predicate"),
    ("presto", "68_assertions_unbound_variable_is_unsupported"),
    ("presto", "69_assertions_assertion_on_limited_predicate"),
    ("presto", "70_assertions_pending_on_missing_helper"),
    ("presto", "71_assertions_assertion_reads_a_value_function"),
    ("psql", "67_assertions_pending_before_its_predicate"),
    ("psql", "68_assertions_unbound_variable_is_unsupported"),
    ("psql", "69_assertions_assertion_on_limited_predicate"),
    ("psql", "70_assertions_pending_on_missing_helper"),
    ("psql", "71_assertions_assertion_reads_a_value_function"),
    ("sqlite", "67_assertions_pending_before_its_predicate"),
    ("sqlite", "68_assertions_unbound_variable_is_unsupported"),
    ("sqlite", "69_assertions_assertion_on_limited_predicate"),
    ("sqlite", "70_assertions_pending_on_missing_helper"),
    ("sqlite", "71_assertions_assertion_reads_a_value_function"),
    ("trino", "67_assertions_pending_before_its_predicate"),
    ("trino", "68_assertions_unbound_variable_is_unsupported"),
    ("trino", "69_assertions_assertion_on_limited_predicate"),
    ("trino", "70_assertions_pending_on_missing_helper"),
    ("trino", "71_assertions_assertion_reads_a_value_function"),
    # @Limit(P, 0): upstream drops the LIMIT.
    ("bigquery", "81_directives_limit_zero"),
    ("databricks", "81_directives_limit_zero"),
    ("duckdb", "81_directives_limit_zero"),
    ("presto", "81_directives_limit_zero"),
    ("psql", "81_directives_limit_zero"),
    ("sqlite", "81_directives_limit_zero"),
    ("trino", "81_directives_limit_zero"),
    # Predicates named like library functions: upstream's type inference fails.
    ("duckdb", "101_execution_functor"),
    ("duckdb", "134_execution_nested_conditional_numbers"),
    ("duckdb", "137_execution_functor_of_a_functor"),
    ("duckdb", "162_execution_predicate_named_like_a_function"),
    ("duckdb", "203_verifier_conditional"),
    ("duckdb", "206_verifier_functor"),
    ("duckdb", "210_verifier_recursion_through_aggregate"),
    ("duckdb", "86_execution_max_min"),
    ("psql", "101_execution_functor"),
    ("psql", "134_execution_nested_conditional_numbers"),
    ("psql", "137_execution_functor_of_a_functor"),
    ("psql", "162_execution_predicate_named_like_a_function"),
    ("psql", "203_verifier_conditional"),
    ("psql", "206_verifier_functor"),
    ("psql", "210_verifier_recursion_through_aggregate"),
    ("psql", "86_execution_max_min"),
    # x in arr: CONTAINS on Presto/Trino.
    ("presto", "99_execution_in_list"),
    ("trino", "99_execution_in_list"),
    # Numbers with a decimal point are DOUBLE on Trino, Presto and Databricks
    # (see DEVIATIONS.md).
    ("databricks", "28_list_membership"),
    ("presto", "28_list_membership"),
    ("trino", "28_list_membership"),
    ("databricks", "121_execution_float_sum"),
    ("presto", "121_execution_float_sum"),
    ("trino", "121_execution_float_sum"),
    ("databricks", "157_execution_float_comparison"),
    ("presto", "157_execution_float_comparison"),
    ("trino", "157_execution_float_comparison"),
    # Count= is exact everywhere; psql's ArgMin/ArgMax keep the value's type
    # (see DEVIATIONS.md).
    ("bigquery", "112_execution_list_aggregate"),
    ("bigquery", "131_execution_count_distinct_value"),
    ("presto", "112_execution_list_aggregate"),
    ("presto", "131_execution_count_distinct_value"),
    ("trino", "112_execution_list_aggregate"),
    ("trino", "131_execution_count_distinct_value"),
    ("databricks", "112_execution_list_aggregate"),
    ("databricks", "131_execution_count_distinct_value"),
    ("psql", "09_argmin_argmax"),
    ("psql", "102_execution_argmax"),
    ("psql", "132_execution_argmin"),
    ("psql", "185_keywords_keyword_column_argmax"),
    ("psql", "29_argmin_argmax"),
    # Batch-1 programs and recursion (see DEVIATIONS.md: StringAgg=, trivially
    # true comparisons, record fields named after keywords, recursion on Presto,
    # what a step of recursion is, and the sections above).
    ("presto", "105_execution_shortest_path"),
    ("presto", "114_execution_negation_of_derived"),
    ("presto", "115_execution_recursion_depth_bounds"),
    ("presto", "138_execution_recursive_count"),
    ("bigquery", "139_execution_mutual_recursion"),
    ("databricks", "139_execution_mutual_recursion"),
    ("presto", "139_execution_mutual_recursion"),
    ("psql", "139_execution_mutual_recursion"),
    ("sqlite", "139_execution_mutual_recursion"),
    ("trino", "139_execution_mutual_recursion"),
    ("presto", "187_recursion_depth_bounds_hops"),
    ("presto", "188_recursion_depth_20_unrolled"),
    ("presto", "200_recursion_depth_one"),
    ("presto", "202_verifier_recursion_with_depth"),
    ("presto", "210_verifier_recursion_through_aggregate"),
    ("databricks", "224_aggregation_float_sum_by_group"),
    ("presto", "224_aggregation_float_sum_by_group"),
    ("trino", "224_aggregation_float_sum_by_group"),
    ("bigquery", "225_aggregation_count_distinct_strings"),
    ("databricks", "225_aggregation_count_distinct_strings"),
    ("presto", "225_aggregation_count_distinct_strings"),
    ("trino", "225_aggregation_count_distinct_strings"),
    ("bigquery", "226_aggregation_string_agg_single"),
    ("databricks", "226_aggregation_string_agg_single"),
    ("presto", "226_aggregation_string_agg_single"),
    ("psql", "226_aggregation_string_agg_single"),
    ("trino", "226_aggregation_string_agg_single"),
    ("databricks", "228_arrays_range_size"),
    ("presto", "228_arrays_range_size"),
    ("trino", "228_arrays_range_size"),
    ("databricks", "229_arrays_range_element"),
    ("presto", "229_arrays_range_element"),
    ("trino", "229_arrays_range_element"),
    ("databricks", "230_arrays_list_aggregate_size"),
    ("presto", "230_arrays_list_aggregate_size"),
    ("trino", "230_arrays_list_aggregate_size"),
    ("databricks", "231_arrays_set_aggregate_size"),
    ("duckdb", "231_arrays_set_aggregate_size"),
    ("presto", "231_arrays_set_aggregate_size"),
    ("trino", "231_arrays_set_aggregate_size"),
    ("databricks", "233_arrays_array_concat"),
    ("presto", "233_arrays_array_concat"),
    ("trino", "233_arrays_array_concat"),
    ("databricks", "234_arrays_array_in_a_fact"),
    ("presto", "234_arrays_array_in_a_fact"),
    ("trino", "234_arrays_array_in_a_fact"),
    ("databricks", "235_arrays_element_out_of_range"),
    ("presto", "235_arrays_element_out_of_range"),
    ("trino", "235_arrays_element_out_of_range"),
    ("databricks", "237_arrays_empty_array"),
    ("duckdb", "237_arrays_empty_array"),
    ("presto", "237_arrays_empty_array"),
    ("psql", "237_arrays_empty_array"),
    ("trino", "237_arrays_empty_array"),
    ("databricks", "238_arrays_array_of_strings_element"),
    ("presto", "238_arrays_array_of_strings_element"),
    ("trino", "238_arrays_array_of_strings_element"),
    ("databricks", "239_arrays_range_sum"),
    ("databricks", "240_casts_string_to_int"),
    ("sqlite", "240_casts_string_to_int"),
    ("databricks", "242_casts_float_to_string"),
    ("presto", "242_casts_float_to_string"),
    ("trino", "242_casts_float_to_string"),
    ("databricks", "243_casts_float_to_int"),
    ("presto", "243_casts_float_to_int"),
    ("sqlite", "243_casts_float_to_int"),
    ("trino", "243_casts_float_to_int"),
    ("databricks", "244_casts_negative_string_to_int"),
    ("sqlite", "244_casts_negative_string_to_int"),
    ("duckdb", "258_joins_three_way"),
    ("psql", "258_joins_three_way"),
    ("databricks", "267_math_floor_ceil"),
    ("presto", "267_math_floor_ceil"),
    ("trino", "267_math_floor_ceil"),
    ("databricks", "268_math_round"),
    ("presto", "268_math_round"),
    ("trino", "268_math_round"),
    ("duckdb", "270_math_exp_log"),
    ("presto", "270_math_exp_log"),
    ("psql", "270_math_exp_log"),
    ("trino", "270_math_exp_log"),
    ("databricks", "274_math_int_equals_float"),
    ("presto", "274_math_int_equals_float"),
    ("trino", "274_math_int_equals_float"),
    ("databricks", "275_math_float_arithmetic_precedence"),
    ("presto", "275_math_float_arithmetic_precedence"),
    ("trino", "275_math_float_arithmetic_precedence"),
    ("duckdb", "277_negation_negation_with_a_constant"),
    ("psql", "277_negation_negation_with_a_constant"),
    ("bigquery", "291_records_nested_record"),
    ("databricks", "291_records_nested_record"),
    ("duckdb", "291_records_nested_record"),
    ("presto", "291_records_nested_record"),
    ("psql", "291_records_nested_record"),
    ("trino", "291_records_nested_record"),
    ("databricks", "294_records_order_by_a_record_field"),
    ("presto", "294_records_order_by_a_record_field"),
    ("trino", "294_records_order_by_a_record_field"),
    ("bigquery", "295_recursion_depth_50"),
    ("databricks", "295_recursion_depth_50"),
    ("duckdb", "295_recursion_depth_50"),
    ("presto", "295_recursion_depth_50"),
    ("psql", "295_recursion_depth_50"),
    ("sqlite", "295_recursion_depth_50"),
    ("trino", "295_recursion_depth_50"),
    ("bigquery", "296_recursion_depth_99"),
    ("databricks", "296_recursion_depth_99"),
    ("duckdb", "296_recursion_depth_99"),
    ("presto", "296_recursion_depth_99"),
    ("psql", "296_recursion_depth_99"),
    ("sqlite", "296_recursion_depth_99"),
    ("trino", "296_recursion_depth_99"),
    ("bigquery", "298_recursion_nonlinear_closure"),
    ("databricks", "298_recursion_nonlinear_closure"),
    ("duckdb", "298_recursion_nonlinear_closure"),
    ("presto", "298_recursion_nonlinear_closure"),
    ("psql", "298_recursion_nonlinear_closure"),
    ("sqlite", "298_recursion_nonlinear_closure"),
    ("trino", "298_recursion_nonlinear_closure"),
    ("bigquery", "300_recursion_semi_naive_with_a_join_and_a_filter"),
    ("databricks", "300_recursion_semi_naive_with_a_join_and_a_filter"),
    ("duckdb", "300_recursion_semi_naive_with_a_join_and_a_filter"),
    ("presto", "300_recursion_semi_naive_with_a_join_and_a_filter"),
    ("psql", "300_recursion_semi_naive_with_a_join_and_a_filter"),
    ("sqlite", "300_recursion_semi_naive_with_a_join_and_a_filter"),
    ("trino", "300_recursion_semi_naive_with_a_join_and_a_filter"),
    ("duckdb", "301_recursion_diamond_closure"),
    ("presto", "301_recursion_diamond_closure"),
    ("bigquery", "302_recursion_bounded_path_lengths"),
    ("databricks", "302_recursion_bounded_path_lengths"),
    ("duckdb", "302_recursion_bounded_path_lengths"),
    ("presto", "302_recursion_bounded_path_lengths"),
    ("psql", "302_recursion_bounded_path_lengths"),
    ("sqlite", "302_recursion_bounded_path_lengths"),
    ("trino", "302_recursion_bounded_path_lengths"),
    ("databricks", "305_strings_length_of_empty"),
    ("databricks", "307_strings_like_underscore"),
    ("databricks", "308_strings_like_is_case_sensitive"),
    ("databricks", "309_strings_split_size"),
    ("presto", "309_strings_split_size"),
    ("trino", "309_strings_split_size"),
    ("databricks", "310_strings_split_element"),
    ("presto", "310_strings_split_element"),
    ("trino", "310_strings_split_element"),
    ("databricks", "312_strings_format"),
    ("presto", "312_strings_format"),
    ("bigquery", "314_strings_escaped_quote"),
    ("databricks", "314_strings_escaped_quote"),
    ("duckdb", "314_strings_escaped_quote"),
    ("presto", "314_strings_escaped_quote"),
    ("psql", "314_strings_escaped_quote"),
    ("sqlite", "314_strings_escaped_quote"),
    ("trino", "314_strings_escaped_quote"),
    ("databricks", "317_strings_length_of_number"),
    ("presto", "35_recursive_annotated"),
    ("presto", "92_execution_transitive_closure"),
    ("bigquery", "322_aggregation_string_agg_two_values"),
    ("databricks", "322_aggregation_string_agg_two_values"),
    ("presto", "322_aggregation_string_agg_two_values"),
    ("psql", "322_aggregation_string_agg_two_values"),
    ("trino", "322_aggregation_string_agg_two_values"),
    ("bigquery", "323_aggregation_string_agg_numbers"),
    ("databricks", "323_aggregation_string_agg_numbers"),
    ("presto", "323_aggregation_string_agg_numbers"),
    ("psql", "323_aggregation_string_agg_numbers"),
    ("trino", "323_aggregation_string_agg_numbers"),
    ("bigquery", "324_aggregation_string_agg_of_nulls"),
    ("databricks", "324_aggregation_string_agg_of_nulls"),
    ("presto", "324_aggregation_string_agg_of_nulls"),
    ("psql", "324_aggregation_string_agg_of_nulls"),
    ("trino", "324_aggregation_string_agg_of_nulls"),
    ("duckdb", "325_recursion_oscillating_aggregate_depth_2"),
    ("presto", "325_recursion_oscillating_aggregate_depth_2"),
    ("duckdb", "326_recursion_oscillating_aggregate_depth_3"),
    ("presto", "326_recursion_oscillating_aggregate_depth_3"),
    ("bigquery", "327_recursion_oscillating_aggregate_depth_24"),
    ("databricks", "327_recursion_oscillating_aggregate_depth_24"),
    ("duckdb", "327_recursion_oscillating_aggregate_depth_24"),
    ("presto", "327_recursion_oscillating_aggregate_depth_24"),
    ("psql", "327_recursion_oscillating_aggregate_depth_24"),
    ("sqlite", "327_recursion_oscillating_aggregate_depth_24"),
    ("trino", "327_recursion_oscillating_aggregate_depth_24"),
    ("bigquery", "328_recursion_oscillating_aggregate_depth_25"),
    ("databricks", "328_recursion_oscillating_aggregate_depth_25"),
    ("duckdb", "328_recursion_oscillating_aggregate_depth_25"),
    ("presto", "328_recursion_oscillating_aggregate_depth_25"),
    ("psql", "328_recursion_oscillating_aggregate_depth_25"),
    ("sqlite", "328_recursion_oscillating_aggregate_depth_25"),
    ("trino", "328_recursion_oscillating_aggregate_depth_25"),
    ("bigquery", "329_recursion_mutual_recursion_exact_depth"),
    ("databricks", "329_recursion_mutual_recursion_exact_depth"),
    ("duckdb", "329_recursion_mutual_recursion_exact_depth"),
    ("presto", "329_recursion_mutual_recursion_exact_depth"),
    ("psql", "329_recursion_mutual_recursion_exact_depth"),
    ("sqlite", "329_recursion_mutual_recursion_exact_depth"),
    ("trino", "329_recursion_mutual_recursion_exact_depth"),
    # Batch 2 (see DEVIATIONS.md: division is exact, a minus after an operator,
    # ordering and limit of a recursion, and the sections above).
    ("bigquery", "105_execution_shortest_path"),
    ("databricks", "105_execution_shortest_path"),
    ("psql", "105_execution_shortest_path"),
    ("sqlite", "105_execution_shortest_path"),
    ("trino", "105_execution_shortest_path"),
    ("bigquery", "115_execution_recursion_depth_bounds"),
    ("databricks", "115_execution_recursion_depth_bounds"),
    ("psql", "115_execution_recursion_depth_bounds"),
    ("sqlite", "115_execution_recursion_depth_bounds"),
    ("trino", "115_execution_recursion_depth_bounds"),
    ("bigquery", "187_recursion_depth_bounds_hops"),
    ("databricks", "187_recursion_depth_bounds_hops"),
    ("psql", "187_recursion_depth_bounds_hops"),
    ("sqlite", "187_recursion_depth_bounds_hops"),
    ("trino", "187_recursion_depth_bounds_hops"),
    ("bigquery", "200_recursion_depth_one"),
    ("databricks", "200_recursion_depth_one"),
    ("psql", "200_recursion_depth_one"),
    ("sqlite", "200_recursion_depth_one"),
    ("trino", "200_recursion_depth_one"),
    ("presto", "214_verifier_aggregate_in_a_combine"),
    ("psql", "214_verifier_aggregate_in_a_combine"),
    ("sqlite", "214_verifier_aggregate_in_a_combine"),
    ("trino", "214_verifier_aggregate_in_a_combine"),
    ("presto", "245_casts_int_division_as_float"),
    ("psql", "245_casts_int_division_as_float"),
    ("sqlite", "245_casts_int_division_as_float"),
    ("trino", "245_casts_int_division_as_float"),
    ("presto", "29_subqueries"),
    ("psql", "29_subqueries"),
    ("sqlite", "29_subqueries"),
    ("trino", "29_subqueries"),
    ("databricks", "330_aggregates_argmax"),
    ("psql", "330_aggregates_argmax"),
    ("databricks", "331_aggregates_argmin_by_group"),
    ("psql", "331_aggregates_argmin_by_group"),
    ("databricks", "332_aggregates_avg_of_floats"),
    ("presto", "332_aggregates_avg_of_floats"),
    ("trino", "332_aggregates_avg_of_floats"),
    ("databricks", "333_aggregates_list_size"),
    ("presto", "333_aggregates_list_size"),
    ("trino", "333_aggregates_list_size"),
    ("databricks", "334_aggregates_set_size"),
    ("duckdb", "334_aggregates_set_size"),
    ("presto", "334_aggregates_set_size"),
    ("trino", "334_aggregates_set_size"),
    ("databricks", "338_aggregates_sum_mixed"),
    ("presto", "338_aggregates_sum_mixed"),
    ("trino", "338_aggregates_sum_mixed"),
    ("databricks", "343_aggregates_argmax_of_a_number"),
    ("psql", "343_aggregates_argmax_of_a_number"),
    ("presto", "344_arithmetic_integer_division"),
    ("psql", "344_arithmetic_integer_division"),
    ("sqlite", "344_arithmetic_integer_division"),
    ("trino", "344_arithmetic_integer_division"),
    ("bigquery", "345_arithmetic_negative_modulo"),
    ("databricks", "345_arithmetic_negative_modulo"),
    ("duckdb", "345_arithmetic_negative_modulo"),
    ("presto", "345_arithmetic_negative_modulo"),
    ("psql", "345_arithmetic_negative_modulo"),
    ("sqlite", "345_arithmetic_negative_modulo"),
    ("trino", "345_arithmetic_negative_modulo"),
    ("bigquery", "346_arithmetic_power"),
    ("databricks", "346_arithmetic_power"),
    ("duckdb", "346_arithmetic_power"),
    ("presto", "346_arithmetic_power"),
    ("psql", "346_arithmetic_power"),
    ("sqlite", "346_arithmetic_power"),
    ("trino", "346_arithmetic_power"),
    ("databricks", "347_arithmetic_float_tolerance"),
    ("presto", "347_arithmetic_float_tolerance"),
    ("trino", "347_arithmetic_float_tolerance"),
    ("databricks", "348_arithmetic_large_integers"),
    ("sqlite", "348_arithmetic_large_integers"),
    ("databricks", "351_arithmetic_sqrt"),
    ("presto", "351_arithmetic_sqrt"),
    ("trino", "351_arithmetic_sqrt"),
    ("databricks", "352_arithmetic_round_half"),
    ("presto", "352_arithmetic_round_half"),
    ("trino", "352_arithmetic_round_half"),
    ("databricks", "353_arithmetic_floor_ceil_negative"),
    ("presto", "353_arithmetic_floor_ceil_negative"),
    ("trino", "353_arithmetic_floor_ceil_negative"),
    ("presto", "354_arithmetic_division_of_columns"),
    ("psql", "354_arithmetic_division_of_columns"),
    ("sqlite", "354_arithmetic_division_of_columns"),
    ("trino", "354_arithmetic_division_of_columns"),
    ("presto", "355_arithmetic_average_of_a_ratio"),
    ("psql", "355_arithmetic_average_of_a_ratio"),
    ("sqlite", "355_arithmetic_average_of_a_ratio"),
    ("trino", "355_arithmetic_average_of_a_ratio"),
    ("databricks", "357_arithmetic_abs_of_a_float"),
    ("presto", "357_arithmetic_abs_of_a_float"),
    ("trino", "357_arithmetic_abs_of_a_float"),
    ("bigquery", "358_arithmetic_unary_minus_after_operators"),
    ("databricks", "358_arithmetic_unary_minus_after_operators"),
    ("duckdb", "358_arithmetic_unary_minus_after_operators"),
    ("presto", "358_arithmetic_unary_minus_after_operators"),
    ("psql", "358_arithmetic_unary_minus_after_operators"),
    ("sqlite", "358_arithmetic_unary_minus_after_operators"),
    ("trino", "358_arithmetic_unary_minus_after_operators"),
    ("databricks", "359_arrays_element_of_a_range"),
    ("presto", "359_arrays_element_of_a_range"),
    ("trino", "359_arrays_element_of_a_range"),
    ("databricks", "360_arrays_concat_with_empty"),
    ("presto", "360_arrays_concat_with_empty"),
    ("psql", "360_arrays_concat_with_empty"),
    ("trino", "360_arrays_concat_with_empty"),
    ("databricks", "361_arrays_list_size_per_group"),
    ("presto", "361_arrays_list_size_per_group"),
    ("trino", "361_arrays_list_size_per_group"),
    ("databricks", "362_arrays_in_a_concatenation"),
    ("presto", "362_arrays_in_a_concatenation"),
    ("databricks", "363_arrays_empty_range"),
    ("presto", "363_arrays_empty_range"),
    ("trino", "363_arrays_empty_range"),
    ("databricks", "364_arrays_set_of_strings_size"),
    ("duckdb", "364_arrays_set_of_strings_size"),
    ("presto", "364_arrays_set_of_strings_size"),
    ("trino", "364_arrays_set_of_strings_size"),
    ("databricks", "375_conditionals_mixed_number_branches"),
    ("presto", "375_conditionals_mixed_number_branches"),
    ("trino", "375_conditionals_mixed_number_branches"),
    ("duckdb", "390_functors_functor_with_null"),
    ("psql", "390_functors_functor_with_null"),
    ("databricks", "400_membership_not_in"),
    ("presto", "400_membership_not_in"),
    ("trino", "400_membership_not_in"),
    ("databricks", "402_membership_in_a_range"),
    ("presto", "40_chained_deps"),
    ("psql", "40_chained_deps"),
    ("sqlite", "40_chained_deps"),
    ("trino", "40_chained_deps"),
    ("databricks", "423_records_nested_field"),
    ("presto", "423_records_nested_field"),
    ("trino", "423_records_nested_field"),
    ("databricks", "425_records_compare_a_field"),
    ("presto", "425_records_compare_a_field"),
    ("trino", "425_records_compare_a_field"),
    ("databricks", "426_recursion_default_depth"),
    ("duckdb", "426_recursion_default_depth"),
    ("presto", "426_recursion_default_depth"),
    ("bigquery", "427_recursion_filtered_closure"),
    ("databricks", "427_recursion_filtered_closure"),
    ("duckdb", "427_recursion_filtered_closure"),
    ("presto", "427_recursion_filtered_closure"),
    ("psql", "427_recursion_filtered_closure"),
    ("sqlite", "427_recursion_filtered_closure"),
    ("trino", "427_recursion_filtered_closure"),
    ("bigquery", "428_recursion_shortest_path"),
    ("databricks", "428_recursion_shortest_path"),
    ("duckdb", "428_recursion_shortest_path"),
    ("presto", "428_recursion_shortest_path"),
    ("psql", "428_recursion_shortest_path"),
    ("sqlite", "428_recursion_shortest_path"),
    ("trino", "428_recursion_shortest_path"),
    ("duckdb", "429_recursion_count_reachable"),
    ("presto", "429_recursion_count_reachable"),
    ("bigquery", "430_recursion_building_strings"),
    ("databricks", "430_recursion_building_strings"),
    ("duckdb", "430_recursion_building_strings"),
    ("presto", "430_recursion_building_strings"),
    ("psql", "430_recursion_building_strings"),
    ("sqlite", "430_recursion_building_strings"),
    ("trino", "430_recursion_building_strings"),
    ("bigquery", "431_recursion_two_base_rules"),
    ("databricks", "431_recursion_two_base_rules"),
    ("duckdb", "431_recursion_two_base_rules"),
    ("presto", "431_recursion_two_base_rules"),
    ("psql", "431_recursion_two_base_rules"),
    ("sqlite", "431_recursion_two_base_rules"),
    ("trino", "431_recursion_two_base_rules"),
    ("bigquery", "433_recursion_depth_21"),
    ("databricks", "433_recursion_depth_21"),
    ("duckdb", "433_recursion_depth_21"),
    ("presto", "433_recursion_depth_21"),
    ("psql", "433_recursion_depth_21"),
    ("sqlite", "433_recursion_depth_21"),
    ("trino", "433_recursion_depth_21"),
    ("bigquery", "434_recursion_limit_of_a_recursion"),
    ("databricks", "434_recursion_limit_of_a_recursion"),
    ("duckdb", "434_recursion_limit_of_a_recursion"),
    ("presto", "434_recursion_limit_of_a_recursion"),
    ("psql", "434_recursion_limit_of_a_recursion"),
    ("sqlite", "434_recursion_limit_of_a_recursion"),
    ("trino", "434_recursion_limit_of_a_recursion"),
    ("bigquery", "436_recursion_limit_of_a_deep_recursion"),
    ("databricks", "436_recursion_limit_of_a_deep_recursion"),
    ("duckdb", "436_recursion_limit_of_a_deep_recursion"),
    ("presto", "436_recursion_limit_of_a_deep_recursion"),
    ("psql", "436_recursion_limit_of_a_deep_recursion"),
    ("sqlite", "436_recursion_limit_of_a_deep_recursion"),
    ("trino", "436_recursion_limit_of_a_deep_recursion"),
    ("databricks", "442_strings_length_unicode"),
    ("databricks", "444_strings_like_percent_inside"),
    ("databricks", "447_strings_split_empty_parts"),
    ("presto", "447_strings_split_empty_parts"),
    ("trino", "447_strings_split_empty_parts"),
    ("databricks", "450_strings_format_integer"),
    ("databricks", "451_strings_format_padding"),
    ("databricks", "461_udf_yesterday"),
    ("sqlite", "461_udf_yesterday"),
    ("databricks", "462_udf_ten_minutes_ago"),
    ("sqlite", "462_udf_ten_minutes_ago"),
    ("bigquery", "92_execution_transitive_closure"),
    ("databricks", "92_execution_transitive_closure"),
    ("psql", "92_execution_transitive_closure"),
    ("sqlite", "92_execution_transitive_closure"),
    ("trino", "92_execution_transitive_closure"),
    ("presto", "97_execution_cast_to_float"),
    ("psql", "97_execution_cast_to_float"),
    ("sqlite", "97_execution_cast_to_float"),
    ("trino", "97_execution_cast_to_float"),
    # Format is lowered on PostgreSQL and Trino too (see DEVIATIONS.md).
    ("psql", "312_strings_format"),
    ("trino", "312_strings_format"),
    ("presto", "450_strings_format_integer"),
    ("psql", "450_strings_format_integer"),
    ("trino", "450_strings_format_integer"),
    ("presto", "451_strings_format_padding"),
    ("psql", "451_strings_format_padding"),
    ("trino", "451_strings_format_padding"),
    ("databricks", "470_strings_format_specifiers"),
    ("presto", "470_strings_format_specifiers"),
    ("psql", "470_strings_format_specifiers"),
    ("trino", "470_strings_format_specifiers"),
    ("psql", "56_format"),
    ("trino", "56_format"),
    # Range of 0 or less, ToString on Trino, aliases equal to a column, ...
    # (see DEVIATIONS.md: engine functions, inlining and correlation).
    ("databricks", "02_arithmetic"),
    ("presto", "02_arithmetic"),
    ("psql", "02_arithmetic"),
    ("trino", "02_arithmetic"),
    ("databricks", "03_comparison"),
    ("presto", "03_comparison"),
    ("psql", "03_comparison"),
    ("trino", "03_comparison"),
    ("databricks", "04_logical_operators"),
    ("presto", "04_logical_operators"),
    ("psql", "04_logical_operators"),
    ("trino", "04_logical_operators"),
    ("bigquery", "103_execution_join"),
    ("databricks", "103_execution_join"),
    ("duckdb", "103_execution_join"),
    ("presto", "103_execution_join"),
    ("psql", "103_execution_join"),
    ("sqlite", "103_execution_join"),
    ("trino", "103_execution_join"),
    ("databricks", "10_negation"),
    ("presto", "10_negation"),
    ("psql", "10_negation"),
    ("trino", "10_negation"),
    ("databricks", "11_disjunction"),
    ("presto", "11_disjunction"),
    ("psql", "11_disjunction"),
    ("trino", "11_disjunction"),
    ("trino", "122_execution_to_string_and_back"),
    ("databricks", "12_if_then_else"),
    ("presto", "12_if_then_else"),
    ("psql", "12_if_then_else"),
    ("trino", "12_if_then_else"),
    ("presto", "149_execution_range"),
    ("psql", "149_execution_range"),
    ("trino", "149_execution_range"),
    ("psql", "14_recursion"),
    ("databricks", "15_annotations"),
    ("presto", "15_annotations"),
    ("psql", "15_annotations"),
    ("trino", "15_annotations"),
    ("bigquery", "17_outer_join"),
    ("duckdb", "17_outer_join"),
    ("sqlite", "17_outer_join"),
    ("psql", "188_recursion_depth_20_unrolled"),
    ("trino", "188_recursion_depth_20_unrolled"),
    ("databricks", "19_type_casting"),
    ("presto", "19_type_casting"),
    ("psql", "19_type_casting"),
    ("trino", "19_type_casting"),
    ("bigquery", "20_list_comprehension"),
    ("databricks", "20_list_comprehension"),
    ("duckdb", "20_list_comprehension"),
    ("presto", "20_list_comprehension"),
    ("psql", "20_list_comprehension"),
    ("sqlite", "20_list_comprehension"),
    ("trino", "20_list_comprehension"),
    ("bigquery", "220_aggregation_arithmetic_on_an_aggregate"),
    ("databricks", "220_aggregation_arithmetic_on_an_aggregate"),
    ("duckdb", "220_aggregation_arithmetic_on_an_aggregate"),
    ("presto", "220_aggregation_arithmetic_on_an_aggregate"),
    ("psql", "220_aggregation_arithmetic_on_an_aggregate"),
    ("sqlite", "220_aggregation_arithmetic_on_an_aggregate"),
    ("trino", "220_aggregation_arithmetic_on_an_aggregate"),
    ("bigquery", "227_aggregation_aggregate_then_filter"),
    ("databricks", "227_aggregation_aggregate_then_filter"),
    ("duckdb", "227_aggregation_aggregate_then_filter"),
    ("presto", "227_aggregation_aggregate_then_filter"),
    ("psql", "227_aggregation_aggregate_then_filter"),
    ("sqlite", "227_aggregation_aggregate_then_filter"),
    ("trino", "227_aggregation_aggregate_then_filter"),
    ("psql", "228_arrays_range_size"),
    ("psql", "229_arrays_range_element"),
    ("databricks", "22_multi_predicate"),
    ("presto", "22_multi_predicate"),
    ("psql", "22_multi_predicate"),
    ("trino", "22_multi_predicate"),
    ("bigquery", "230_arrays_list_aggregate_size"),
    ("duckdb", "230_arrays_list_aggregate_size"),
    ("psql", "230_arrays_list_aggregate_size"),
    ("sqlite", "230_arrays_list_aggregate_size"),
    ("bigquery", "231_arrays_set_aggregate_size"),
    ("psql", "231_arrays_set_aggregate_size"),
    ("sqlite", "231_arrays_set_aggregate_size"),
    ("bigquery", "232_arrays_membership_in_a_collected_list"),
    ("databricks", "232_arrays_membership_in_a_collected_list"),
    ("duckdb", "232_arrays_membership_in_a_collected_list"),
    ("presto", "232_arrays_membership_in_a_collected_list"),
    ("psql", "232_arrays_membership_in_a_collected_list"),
    ("sqlite", "232_arrays_membership_in_a_collected_list"),
    ("trino", "232_arrays_membership_in_a_collected_list"),
    ("bigquery", "234_arrays_array_in_a_fact"),
    ("duckdb", "234_arrays_array_in_a_fact"),
    ("psql", "234_arrays_array_in_a_fact"),
    ("sqlite", "234_arrays_array_in_a_fact"),
    ("bigquery", "237_arrays_empty_array"),
    ("sqlite", "237_arrays_empty_array"),
    ("presto", "239_arrays_range_sum"),
    ("psql", "239_arrays_range_sum"),
    ("trino", "239_arrays_range_sum"),
    ("trino", "246_casts_null_to_string"),
    ("trino", "247_casts_int_to_string_and_compare"),
    ("psql", "24_udf"),
    ("databricks", "25_inline_annotations"),
    ("presto", "25_inline_annotations"),
    ("psql", "25_inline_annotations"),
    ("trino", "25_inline_annotations"),
    ("bigquery", "263_joins_join_on_two_columns"),
    ("databricks", "263_joins_join_on_two_columns"),
    ("duckdb", "263_joins_join_on_two_columns"),
    ("presto", "263_joins_join_on_two_columns"),
    ("psql", "263_joins_join_on_two_columns"),
    ("sqlite", "263_joins_join_on_two_columns"),
    ("trino", "263_joins_join_on_two_columns"),
    ("bigquery", "264_joins_join_on_a_computed_key"),
    ("databricks", "264_joins_join_on_a_computed_key"),
    ("duckdb", "264_joins_join_on_a_computed_key"),
    ("presto", "264_joins_join_on_a_computed_key"),
    ("psql", "264_joins_join_on_a_computed_key"),
    ("sqlite", "264_joins_join_on_a_computed_key"),
    ("trino", "264_joins_join_on_a_computed_key"),
    ("databricks", "26_builtin_functions"),
    ("presto", "26_builtin_functions"),
    ("psql", "26_builtin_functions"),
    ("trino", "26_builtin_functions"),
    ("bigquery", "276_negation_double_negation"),
    ("databricks", "276_negation_double_negation"),
    ("duckdb", "276_negation_double_negation"),
    ("presto", "276_negation_double_negation"),
    ("psql", "276_negation_double_negation"),
    ("sqlite", "276_negation_double_negation"),
    ("trino", "276_negation_double_negation"),
    ("bigquery", "279_negation_negation_of_an_aggregate"),
    ("databricks", "279_negation_negation_of_an_aggregate"),
    ("duckdb", "279_negation_negation_of_an_aggregate"),
    ("presto", "279_negation_negation_of_an_aggregate"),
    ("psql", "279_negation_negation_of_an_aggregate"),
    ("sqlite", "279_negation_negation_of_an_aggregate"),
    ("trino", "279_negation_negation_of_an_aggregate"),
    ("databricks", "27_assignment"),
    ("presto", "27_assignment"),
    ("psql", "27_assignment"),
    ("trino", "27_assignment"),
    ("databricks", "27_boolean_ops"),
    ("presto", "27_boolean_ops"),
    ("psql", "27_boolean_ops"),
    ("trino", "27_boolean_ops"),
    ("databricks", "28_multi_rule_predicate"),
    ("presto", "28_multi_rule_predicate"),
    ("psql", "28_multi_rule_predicate"),
    ("trino", "28_multi_rule_predicate"),
    ("bigquery", "294_records_order_by_a_record_field"),
    ("duckdb", "294_records_order_by_a_record_field"),
    ("psql", "294_records_order_by_a_record_field"),
    ("sqlite", "294_records_order_by_a_record_field"),
    ("trino", "303_strings_concat_number"),
    ("databricks", "30_complex_expressions"),
    ("presto", "30_complex_expressions"),
    ("psql", "30_complex_expressions"),
    ("trino", "30_complex_expressions"),
    ("databricks", "311_strings_join"),
    ("presto", "311_strings_join"),
    ("trino", "311_strings_join"),
    ("trino", "317_strings_length_of_number"),
    ("bigquery", "31_self_join_conditions"),
    ("databricks", "31_self_join_conditions"),
    ("duckdb", "31_self_join_conditions"),
    ("presto", "31_self_join_conditions"),
    ("psql", "31_self_join_conditions"),
    ("sqlite", "31_self_join_conditions"),
    ("trino", "31_self_join_conditions"),
    ("databricks", "31_user_functions"),
    ("presto", "31_user_functions"),
    ("psql", "31_user_functions"),
    ("trino", "31_user_functions"),
    ("duckdb", "322_aggregation_string_agg_two_values"),
    ("sqlite", "322_aggregation_string_agg_two_values"),
    ("bigquery", "333_aggregates_list_size"),
    ("duckdb", "333_aggregates_list_size"),
    ("psql", "333_aggregates_list_size"),
    ("sqlite", "333_aggregates_list_size"),
    ("bigquery", "334_aggregates_set_size"),
    ("psql", "334_aggregates_set_size"),
    ("sqlite", "334_aggregates_set_size"),
    ("bigquery", "340_aggregates_any_value_of_equal_values"),
    ("databricks", "340_aggregates_any_value_of_equal_values"),
    ("duckdb", "340_aggregates_any_value_of_equal_values"),
    ("presto", "340_aggregates_any_value_of_equal_values"),
    ("psql", "340_aggregates_any_value_of_equal_values"),
    ("sqlite", "340_aggregates_any_value_of_equal_values"),
    ("trino", "340_aggregates_any_value_of_equal_values"),
    ("psql", "359_arrays_element_of_a_range"),
    ("bigquery", "360_arrays_concat_with_empty"),
    ("duckdb", "360_arrays_concat_with_empty"),
    ("sqlite", "360_arrays_concat_with_empty"),
    ("bigquery", "361_arrays_list_size_per_group"),
    ("duckdb", "361_arrays_list_size_per_group"),
    ("psql", "361_arrays_list_size_per_group"),
    ("sqlite", "361_arrays_list_size_per_group"),
    ("psql", "363_arrays_empty_range"),
    ("bigquery", "364_arrays_set_of_strings_size"),
    ("psql", "364_arrays_set_of_strings_size"),
    ("sqlite", "364_arrays_set_of_strings_size"),
    ("databricks", "36_range_operations"),
    ("presto", "36_range_operations"),
    ("psql", "36_range_operations"),
    ("trino", "36_range_operations"),
    ("bigquery", "399_membership_in_a_collected_list"),
    ("databricks", "399_membership_in_a_collected_list"),
    ("duckdb", "399_membership_in_a_collected_list"),
    ("presto", "399_membership_in_a_collected_list"),
    ("psql", "399_membership_in_a_collected_list"),
    ("sqlite", "399_membership_in_a_collected_list"),
    ("trino", "399_membership_in_a_collected_list"),
    ("presto", "402_membership_in_a_range"),
    ("psql", "402_membership_in_a_range"),
    ("trino", "402_membership_in_a_range"),
    ("bigquery", "404_negation_double_negation"),
    ("databricks", "404_negation_double_negation"),
    ("duckdb", "404_negation_double_negation"),
    ("presto", "404_negation_double_negation"),
    ("psql", "404_negation_double_negation"),
    ("sqlite", "404_negation_double_negation"),
    ("trino", "404_negation_double_negation"),
    ("bigquery", "405_negation_negation_of_an_aggregate"),
    ("databricks", "405_negation_negation_of_an_aggregate"),
    ("duckdb", "405_negation_negation_of_an_aggregate"),
    ("presto", "405_negation_negation_of_an_aggregate"),
    ("psql", "405_negation_negation_of_an_aggregate"),
    ("sqlite", "405_negation_negation_of_an_aggregate"),
    ("trino", "405_negation_negation_of_an_aggregate"),
    ("bigquery", "413_nulls_null_keys_do_not_join"),
    ("databricks", "413_nulls_null_keys_do_not_join"),
    ("duckdb", "413_nulls_null_keys_do_not_join"),
    ("presto", "413_nulls_null_keys_do_not_join"),
    ("psql", "413_nulls_null_keys_do_not_join"),
    ("sqlite", "413_nulls_null_keys_do_not_join"),
    ("trino", "413_nulls_null_keys_do_not_join"),
    ("databricks", "41_edge_arithmetic"),
    ("presto", "41_edge_arithmetic"),
    ("psql", "41_edge_arithmetic"),
    ("trino", "41_edge_arithmetic"),
    ("psql", "426_recursion_default_depth"),
    ("trino", "426_recursion_default_depth"),
    ("databricks", "448_strings_join_a_split"),
    ("presto", "448_strings_join_a_split"),
    ("trino", "448_strings_join_a_split"),
    ("trino", "458_udf_pad2"),
    ("trino", "461_udf_yesterday"),
    ("trino", "462_udf_ten_minutes_ago"),
    ("databricks", "46_constraint"),
    ("presto", "46_constraint"),
    ("psql", "46_constraint"),
    ("trino", "46_constraint"),
    ("databricks", "471_arrays_range_of_negative_size"),
    ("presto", "471_arrays_range_of_negative_size"),
    ("psql", "471_arrays_range_of_negative_size"),
    ("trino", "471_arrays_range_of_negative_size"),
    ("databricks", "472_casts_nested_conversions"),
    ("presto", "472_casts_nested_conversions"),
    ("sqlite", "472_casts_nested_conversions"),
    ("trino", "472_casts_nested_conversions"),
    ("databricks", "477_strings_tostring_of_a_fraction"),
    ("presto", "477_strings_tostring_of_a_fraction"),
    ("trino", "477_strings_tostring_of_a_fraction"),
    ("trino", "53_temporal"),
    ("bigquery", "54_sqlexpr"),
    ("databricks", "54_sqlexpr"),
    ("duckdb", "54_sqlexpr"),
    ("presto", "54_sqlexpr"),
    ("psql", "54_sqlexpr"),
    ("sqlite", "54_sqlexpr"),
    ("trino", "54_sqlexpr"),
    ("trino", "61_date_arithmetic"),
    ("sqlite", "464_udf_function_of_null"),
    ("duckdb", "464_udf_function_of_null"),
    ("psql", "464_udf_function_of_null"),
    ("bigquery", "464_udf_function_of_null"),
    ("trino", "464_udf_function_of_null"),
    ("presto", "464_udf_function_of_null"),
    ("databricks", "464_udf_function_of_null"),
    # Databricks iterates every recursion (see DEVIATIONS.md).
    ("databricks", "114_execution_negation_of_derived"),
    ("databricks", "138_execution_recursive_count"),
    ("databricks", "202_verifier_recursion_with_depth"),
    ("databricks", "210_verifier_recursion_through_aggregate"),
    ("databricks", "301_recursion_diamond_closure"),
    ("databricks", "325_recursion_oscillating_aggregate_depth_2"),
    ("databricks", "326_recursion_oscillating_aggregate_depth_3"),
    ("databricks", "35_recursive_annotated"),
    ("databricks", "429_recursion_count_reachable"),
    # Databricks unnests in a LATERAL subquery (see DEVIATIONS.md).
    ("databricks", "06_arrays"),
    ("databricks", "101_execution_functor"),
    ("databricks", "106_execution_predicate_named_order"),
    ("databricks", "110_execution_comparison_chain"),
    ("databricks", "111_execution_not_equal"),
    ("databricks", "113_execution_average"),
    ("databricks", "116_execution_sum_over_nothing"),
    ("databricks", "124_execution_zero_column_predicate"),
    ("databricks", "125_execution_negated_zero_column_predicate"),
    ("databricks", "133_execution_disjunction_of_conjunctions"),
    ("databricks", "134_execution_nested_conditional_numbers"),
    ("databricks", "135_execution_import"),
    ("databricks", "136_execution_import_with_alias"),
    ("databricks", "137_execution_functor_of_a_functor"),
    ("databricks", "141_execution_limit_without_order"),
    ("databricks", "143_execution_comparison_of_strings"),
    ("databricks", "144_execution_grouped_aggregate_over_nothing"),
    ("databricks", "145_execution_distinct_union"),
    ("databricks", "152_execution_string_max"),
    ("databricks", "154_execution_negation_keyword_names"),
    ("databricks", "162_execution_predicate_named_like_a_function"),
    ("databricks", "166_front_matter_no_front_matter_is_not_checked"),
    ("databricks", "173_keywords_predicate_order"),
    ("databricks", "184_keywords_keyword_column_functor"),
    ("databricks", "201_verifier_safe_negation"),
    ("databricks", "203_verifier_conditional"),
    ("databricks", "204_verifier_disjunction"),
    ("databricks", "205_verifier_several_aggregates"),
    ("databricks", "206_verifier_functor"),
    ("databricks", "207_verifier_in_a_list"),
    ("databricks", "211_verifier_assignment_binds"),
    ("databricks", "212_verifier_head_constant"),
    ("databricks", "213_verifier_value_function"),
    ("databricks", "214_verifier_aggregate_in_a_combine"),
    ("databricks", "215_verifier_negation_of_a_conjunction"),
    ("databricks", "217_aggregation_average_of_integers"),
    ("databricks", "218_aggregation_min_of_strings"),
    ("databricks", "223_aggregation_max_of_an_expression"),
    ("databricks", "236_arrays_unnest_a_held_array"),
    ("databricks", "23_set_operations"),
    ("databricks", "247_casts_int_to_string_and_compare"),
    ("databricks", "248_directives_limit_desc_page"),
    ("databricks", "249_directives_search_numbers"),
    ("databricks", "250_directives_page_past_the_end"),
    ("databricks", "251_directives_ground_then_use"),
    ("databricks", "255_functions_conditional_function"),
    ("databricks", "256_functions_function_in_an_aggregate"),
    ("databricks", "257_functions_function_in_a_filter"),
    ("databricks", "259_joins_join_with_a_filter"),
    ("databricks", "260_joins_ordered_pairs"),
    ("databricks", "262_joins_cross_product"),
    ("databricks", "265_joins_union_of_matched_and_unmatched"),
    ("databricks", "277_negation_negation_with_a_constant"),
    ("databricks", "278_negation_negation_in_a_disjunction_branch"),
    ("databricks", "280_negation_negation_of_an_empty_predicate"),
    ("databricks", "281_negation_negation_on_strings"),
    ("databricks", "313_strings_order_by_case"),
    ("databricks", "318_unions_three_branches_distinct"),
    ("databricks", "319_unions_same_predicate_two_filters"),
    ("databricks", "320_unions_union_keeps_duplicates"),
    ("databricks", "321_unions_union_with_negation"),
    ("databricks", "336_aggregates_sum_of_nothing"),
    ("databricks", "339_aggregates_group_by_an_expression"),
    ("databricks", "341_aggregates_max_of_dates"),
    ("databricks", "342_aggregates_count_and_sum"),
    ("databricks", "365_boolean_negated_comparison"),
    ("databricks", "366_boolean_precedence"),
    ("databricks", "367_boolean_boolean_column"),
    ("databricks", "368_boolean_filter_on_a_boolean_column"),
    ("databricks", "369_boolean_count_true"),
    ("databricks", "372_conditionals_nested"),
    ("databricks", "373_conditionals_null_branch"),
    ("databricks", "374_conditionals_count_with_a_conditional"),
    ("databricks", "376_conditionals_condition_on_strings"),
    ("databricks", "377_conditionals_boolean_connectives"),
    ("databricks", "378_conditionals_group_by_a_conditional"),
    ("databricks", "382_dedup_union_keeps_duplicates"),
    ("databricks", "384_functors_substitute_a_predicate"),
    ("databricks", "385_functors_two_applications"),
    ("databricks", "389_functors_result_used_in_a_rule"),
    ("databricks", "392_joins_self_join_pairs"),
    ("databricks", "394_joins_default_for_missing"),
    ("databricks", "396_joins_cross_join_count"),
    ("databricks", "398_membership_in_a_literal_list"),
    ("databricks", "401_membership_strings"),
    ("databricks", "403_membership_in_a_split"),
    ("databricks", "407_negation_negation_of_a_union"),
    ("databricks", "414_ordering_descending"),
    ("databricks", "416_ordering_limit_after_order"),
    ("databricks", "417_ordering_strings_order_by_text"),
    ("databricks", "418_ordering_top_aggregate"),
    ("databricks", "419_ordering_order_by_a_computed_column"),
    ("databricks", "41_import_basic"),
    ("databricks", "420_ordering_page"),
    ("databricks", "421_ordering_page_with_limit"),
    ("databricks", "42_builtin_funcs"),
    ("databricks", "42_import_alias"),
    ("databricks", "437_search_search_strings"),
    ("databricks", "438_search_search_no_match"),
    ("databricks", "43_import_multiple"),
    ("databricks", "440_search_search_digits"),
    ("databricks", "445_strings_string_comparison"),
    ("databricks", "452_strings_substr_of_a_column"),
    ("databricks", "456_udf_conditional_function"),
    ("databricks", "459_udf_function_in_an_aggregate"),
    ("databricks", "45_import_string"),
    ("databricks", "460_udf_boolean_function_compared"),
    ("databricks", "465_udf_function_per_row"),
    ("databricks", "468_unions_union_then_count_distinct"),
    ("databricks", "476_search_search_keeps_the_order"),
    ("databricks", "72_directives_page"),
    ("databricks", "73_directives_page_within_limit"),
    ("databricks", "74_directives_offset_past_limit"),
    ("databricks", "76_directives_search_ordered"),
    ("databricks", "77_directives_recursive_on_non_recursive"),
    ("databricks", "79_directives_order_by_desc_lowercase"),
    ("databricks", "82_directives_order_by_imported_predicate"),
    ("databricks", "83_directives_order_by_functor_result"),
    ("databricks", "84_execution_count"),
    ("databricks", "86_execution_max_min"),
    ("databricks", "89_execution_negation"),
    ("databricks", "90_execution_disjunction"),
    ("databricks", "93_execution_limit"),
    ("databricks", "94_execution_order_desc"),
    ("databricks", "95_execution_conditional"),
    # ToInt64 rounds a float on SQLite and Databricks (see DEVIATIONS.md).
    ("sqlite", "61_date_arithmetic"),
    ("sqlite", "122_execution_to_string_and_back"),
    ("databricks", "61_date_arithmetic"),
    ("databricks", "122_execution_to_string_and_back"),
    ("psql", "55_argmax_k"),
}

# Goldens intentionally absent because synalog lacks the subsystem
# (DEVIATIONS.md). Currently none.
ABSENT_GOLDENS = set()


def last_predicate(rules, source):
    """The predicate of the last rule the fixture itself writes — same
    convention as the Rust golden tests (tests/common/mod.rs), which explain
    it: by the position of each rule's text (`full_text`) in the source."""
    last, last_position = None, 0
    for r in rules:
        name = r.get('head', {}).get('predicate_name')
        if name == '@Make':
            name = made_predicate(r['head'])
        position = source.find(r.get('full_text', '\0'))
        if position >= last_position and name and not name.startswith(('@', '_')):
            last, last_position = name, position
    return last


def made_predicate(head):
    """The predicate an `@Make` head (`F := G(...)`) defines: its first argument."""
    try:
        value = head["record"]["field_value"][0]["value"]
        return value.get("expression", value)["literal"]["the_predicate"]["predicate_name"]
    except (KeyError, IndexError, TypeError):
        return None


class TimeoutError(Exception):
    pass


def _timeout_handler(signum, frame):
    raise TimeoutError("Compilation timed out")


import re as _re

def _with_engine(source, engine):
    """An @Engine line first — after the YAML front matter when the file opens
    with one (front matter must open the file); same as tests/common/mod.rs."""
    annotation = '@Engine("{}");\n'.format(engine)
    lines = source.splitlines(keepends=True)
    if lines and lines[0].rstrip() == '---':
        for i, line in enumerate(lines[1:], 1):
            if line.rstrip() == '---':
                return ''.join(lines[:i + 1]) + annotation + ''.join(lines[i + 1:])
    return annotation + source


def _strip_engine(source):
    """Remove @Engine(...) annotation from source."""
    return _re.sub(r'@Engine\([^)]*\)\s*;?\s*', '', source)


def fixture_stems(engine):
    """Canonical fixture stems plus the engine's overrides/engine-only fixtures."""
    stems = set()
    for pattern in ("fixtures/*.l", f"{engine}/*.l"):
        for path in glob.glob(pattern):
            stems.add(os.path.splitext(os.path.basename(path))[0])
    return sorted(stems)


def fixture_source(engine, stem):
    """Engine-specific override wins over the canonical fixture."""
    override = os.path.join(engine, f"{stem}.l")
    if os.path.exists(override):
        return override
    return os.path.join("fixtures", f"{stem}.l")


def generate_for_file(l_path, engine, timeout=30):
    """Try to compile a .l file. Returns (predicate, sql) or error tuple."""
    source = open(l_path).read()
    source = _with_engine(_strip_engine(source), engine)

    old_handler = signal.signal(signal.SIGALRM, _timeout_handler)
    signal.alarm(timeout)
    try:
        parsed = logica_parse.ParseFile(source)['rule']

        pred = last_predicate(parsed, source)
        if pred is None:
            return None
        program = universe.LogicaProgram(parsed, user_flags={})
        sql = program.FormattedPredicateSql(pred)
        return (pred, sql)
    except TimeoutError:
        return ("timeout", None)
    except Exception as e:
        return ("error", str(e))
    finally:
        signal.alarm(0)
        signal.signal(signal.SIGALRM, old_handler)


def process_engine(engine):
    """Generate goldens for all of an engine's fixtures."""
    stems = fixture_stems(engine)
    print(f"\n=== Processing {engine} ({len(stems)} fixtures) ===")

    stats = {"ok": 0, "timeout": 0, "no_pred": 0, "error": 0, "protected": 0}
    errors = {}

    for stem in stems:
        if stem.endswith("_fail"):
            continue
        print(f"  {stem}...", end=" ", flush=True)

        if (engine, stem) in SYNALOG_GOLDENS or (engine, stem) in ABSENT_GOLDENS:
            stats["protected"] += 1
            print("SKIP (protected, see DEVIATIONS.md)")
            continue

        result = generate_for_file(fixture_source(engine, stem), engine)

        if result is None:
            stats["no_pred"] += 1
            print("SKIP (no predicates)")
            continue
        if result[0] == "timeout":
            stats["timeout"] += 1
            print("SKIP (timeout)")
            continue
        if result[0] == "error":
            stats["error"] += 1
            errors[stem] = result[1]
            print(f"ERROR: {result[1][:60]}...")
            continue

        pred, sql = result
        with open(os.path.join(engine, f"{stem}.sql"), 'w') as f:
            f.write(sql)

        stats["ok"] += 1
        print(f"OK ({pred})")

    return stats, errors


def main():
    print("Generating expected SQL for compiler tests...")

    all_stats = {}
    all_errors = {}

    for engine in ENGINES:
        if os.path.isdir(os.path.join(SCRIPT_DIR, engine)):
            stats, errors = process_engine(engine)
            all_stats[engine] = stats
            all_errors[engine] = errors

    print(f"\n{'='*50}")
    print("SUMMARY")
    print(f"{'='*50}")

    for engine, stats in all_stats.items():
        total = sum(stats.values())
        print(f"\n{engine.upper()}:")
        print(f"  OK:          {stats['ok']}/{total}")
        print(f"  Protected:   {stats['protected']}/{total}")
        print(f"  Timeout:     {stats['timeout']}/{total}")
        print(f"  No predicate:{stats['no_pred']}/{total}")
        print(f"  Errors:      {stats['error']}/{total}")

        if all_errors.get(engine):
            print(f"\n  Errors detail:")
            for name, err in all_errors[engine].items():
                print(f"    - {name}: {err[:80]}")

    print(f"\nSQL files written to engine directories")


if __name__ == "__main__":
    main()
