# Test: Whether everyone gus follows is older: no one followed is not. (from tests/programs/negation3/follows_only_older_gus.l)

U(u: "ann", age: 31);
U(u: "bob", age: 25);
U(u: "cid", age: 40);
U(u: "dee", age: 19);
U(u: "eve", age: 52);
U(u: "fay", age: 28);
U(u: "gus", age: 35);
F(a: "ann", b: "bob");
F(a: "bob", b: "ann");
F(a: "bob", b: "cid");
F(a: "cid", b: "dee");
F(a: "dee", b: "cid");
F(a: "eve", b: "ann");
F(a: "fay", b: "fay");
F(a: "ann", b: "cid");
Q(x: 1) :- U(u: "gus", age: me), ~(F(a: "gus", b: v), U(u: v, age: a), a <= me);
