//! Compiler feature tests: comprehensive Logica feature coverage for all SQL engines.
//!
//! These tests verify the Rust compiler against expected SQL golden files
//! (generated by Python Logica, except for the documented deviations in
//! compiler_tests/DEVIATIONS.md).
//!
//! Layout: canonical engine-independent sources live in
//! compiler_tests/fixtures/*.l; each engine directory holds the golden
//! .sql files plus optional .l overrides for programs that genuinely differ
//! on that engine (and engine-only fixtures). A fixture runs for an engine
//! when that engine has a golden .sql for it.
//!
//! Note: Type preambles (logicarecord type definitions) are stripped before comparison
//! because the Rust compiler doesn't yet generate them (see TODO in universe.rs).

mod common;

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::mpsc;
use std::time::Duration;

use synalog::compiler::universe::LogicaProgram;
use synalog::parser::parse_file;

use common::{last_predicate, strip_engine};

/// Strip type preamble definitions from SQL and normalize for comparison.
///
/// This normalizes:
/// 1. Type preamble definitions (logicarecord types) - not generated by Rust yet
/// 2. Type annotations (::text[], ::numeric[]) - not generated by Rust yet
/// 3. Multiple blank lines
/// 4. Variable names (x_N where N is a number) - Python and Rust may use different numbers
fn normalize_sql_for_comparison(sql: &str) -> String {
    let mut lines: Vec<&str> = Vec::new();
    let mut in_do_block = false;

    for line in sql.lines() {
        let trimmed = line.trim();

        // Skip DuckDB type definition lines (comment + drop/create on same or separate lines)
        if trimmed.starts_with("-- Logica type:") {
            continue;
        }
        // Skip combined drop/create type lines for DuckDB
        if trimmed.starts_with("drop type if exists logicarecord") {
            continue;
        }

        // Skip PostgreSQL DO $$ blocks for type definitions
        if trimmed.starts_with("DO $$") && trimmed.contains("logicarecord") {
            continue;
        }
        if trimmed == "DO $$" {
            in_do_block = true;
            continue;
        }
        if in_do_block {
            if trimmed == "END $$;" {
                in_do_block = false;
            }
            continue;
        }

        lines.push(line);
    }

    // Join lines
    let joined = lines.join("\n");

    // Remove type casts like ::text[], ::numeric[], ::bigint[] etc.
    // These are added by Python's type inference but Rust doesn't add them yet
    let type_cast_re = regex::Regex::new(r"::\w+\[\]").unwrap();
    let no_casts = type_cast_re.replace_all(&joined, "");

    // Remove scalar composite-type casts like `::logicarecord462007516`.
    // The `logicarecordNNN` suffix is an arbitrary per-type hash that differs
    // between upstream Logica and synalog; the type *definitions* are already
    // stripped above (preamble lines / DO $$ blocks), so dropping the inline
    // cast keeps the comparison about query logic, not the hash identifier.
    let composite_cast_re = regex::Regex::new(r"::logicarecord\d+").unwrap();
    let no_casts = composite_cast_re.replace_all(&no_casts, "");

    // Normalize variable names (x_N) to consistent placeholder
    // Python and Rust may generate different variable numbers
    let var_re = regex::Regex::new(r"\bx_\d+\b").unwrap();
    let normalized_vars = normalize_variable_names(&no_casts, &var_re);

    // Normalize WHERE clause condition ordering
    // Conditions connected by AND may appear in different orders
    let normalized_where = normalize_where_clauses(&normalized_vars);

    // Collapse multiple blank lines into single blank lines
    let blank_re = regex::Regex::new(r"\n\n+").unwrap();
    blank_re.replace_all(&normalized_where, "\n\n").trim().to_string()
}

/// Normalize WHERE clause by sorting AND conditions alphabetically.
fn normalize_where_clauses(sql: &str) -> String {
    let mut result = String::new();
    let mut remaining = sql;

    while let Some(where_start) = remaining.find("WHERE") {
        // Copy everything before WHERE
        result.push_str(&remaining[..where_start]);
        remaining = &remaining[where_start..];

        // Find the end of the WHERE clause
        let where_end = remaining[5..] // skip "WHERE"
            .find("ORDER BY")
            .or_else(|| remaining[5..].find("GROUP BY"))
            .or_else(|| remaining[5..].find(" LIMIT"))
            .or_else(|| remaining[5..].find(");"))
            .map(|i| i + 5)
            .unwrap_or(remaining.len());

        let where_clause = &remaining[5..where_end]; // skip "WHERE"

        // Split by AND
        let and_re = regex::Regex::new(r"\s+AND\s*\n?\s*").unwrap();
        let conditions: Vec<&str> = and_re.split(where_clause.trim()).collect();

        // Clean up and sort
        let mut cleaned: Vec<String> = conditions.iter()
            .map(|c| c.trim().to_string())
            .filter(|c| !c.is_empty())
            .collect();
        cleaned.sort();

        // Rebuild WHERE clause
        result.push_str("WHERE\n  ");
        result.push_str(&cleaned.join(" AND\n  "));

        remaining = &remaining[where_end..];
    }

    result.push_str(remaining);
    result
}

/// Normalize variable names by replacing x_N with x_M where M is determined by order of appearance.
fn normalize_variable_names(sql: &str, var_re: &regex::Regex) -> String {
    use std::collections::HashMap;
    let mut var_map: HashMap<String, String> = HashMap::new();
    let mut counter = 0;

    var_re.replace_all(sql, |caps: &regex::Captures| {
        let var = caps[0].to_string();
        let normalized = var_map.entry(var).or_insert_with(|| {
            let name = format!("x_{}", counter);
            counter += 1;
            name
        });
        normalized.clone()
    }).to_string()
}

/// Path to the compiler_tests directory.
fn compiler_tests_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/compiler_tests")
}

/// Import roots for resolving imports.
fn import_roots() -> Vec<String> {
    vec![compiler_tests_dir().to_str().unwrap().to_string()]
}

/// Known failures that are expected to fail (complex features not yet implemented).
fn known_failures(_engine: &str) -> std::collections::HashSet<&'static str> {
    std::collections::HashSet::new()
}

/// Fixture stems for an engine: canonical fixtures/*.l plus any .l in the
/// engine directory (overrides and engine-only fixtures), deduplicated.
fn fixture_stems(engine_dir: &std::path::Path, fail_tests: bool) -> Vec<String> {
    let mut stems = std::collections::BTreeSet::new();
    let fixtures_dir = compiler_tests_dir().join("fixtures");
    for dir in [&fixtures_dir, &engine_dir.to_path_buf()] {
        if !dir.exists() {
            continue;
        }
        for entry in std::fs::read_dir(dir).unwrap().filter_map(|e| e.ok()) {
            if let Some(name) = entry.file_name().to_str() {
                if name.ends_with(".l") && (name.ends_with("_fail.l") == fail_tests) {
                    stems.insert(name[..name.len() - 2].to_string());
                }
            }
        }
    }
    stems.into_iter().collect()
}

/// Source path for a fixture: the engine-specific override wins over the
/// canonical fixture.
fn fixture_source(engine_dir: &std::path::Path, stem: &str) -> PathBuf {
    let override_path = engine_dir.join(format!("{}.l", stem));
    if override_path.exists() {
        override_path
    } else {
        compiler_tests_dir().join("fixtures").join(format!("{}.l", stem))
    }
}

/// Run compiler tests for a specific engine (duckdb or psql).
fn run_compiler_feature_tests(engine: &str) {
    let dir = compiler_tests_dir().join(engine);
    let known_fail = known_failures(engine);

    if !dir.exists() {
        panic!("compiler_tests/{}/ directory not found", engine);
    }

    let stems = fixture_stems(&dir, false);

    let mut matched = 0;
    let mut mismatched = Vec::new();
    let mut errored = Vec::new();
    let mut timed_out = Vec::new();
    let mut missing_sql = Vec::new();
    let mut total = 0;

    for stem in &stems {
        let stem = stem.as_str();

        let sql_path = dir.join(format!("{}.sql", stem));
        if !sql_path.exists() {
            missing_sql.push(stem.to_string());
            continue;
        }

        total += 1;
        let source = std::fs::read_to_string(fixture_source(&dir, stem)).unwrap();
        let expected_sql = std::fs::read_to_string(&sql_path).unwrap();

        // Strip existing engine annotation and add the correct one
        let clean = strip_engine(&source);
        let full_source = format!("@Engine(\"{}\");\n{}", engine, clean);

        let full_source_clone = full_source.clone();
        let stem_str = stem.to_string();
        let roots = import_roots();
        let (tx, rx) = mpsc::channel();

        let _handle = std::thread::Builder::new()
            .stack_size(512 * 1024 * 1024)
            .spawn(move || {
                let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    let parsed =
                        parse_file(&full_source_clone, None, &roots).expect("parse failed");
                    let pred = last_predicate(&parsed)
                        .unwrap_or_else(|| panic!("No predicate found in {}", stem_str));
                    let program = LogicaProgram::new(&parsed, HashMap::new(), HashMap::new())
                        .expect("program creation failed");
                    let sql = program
                        .formatted_predicate_sql(&pred)
                        .expect("SQL compilation failed");
                    (pred, sql)
                }));
                let _ = tx.send(result);
            })
            .unwrap();

        let is_known_fail = known_fail.contains(stem);

        match rx.recv_timeout(Duration::from_secs(30)) {
            Ok(Ok((_pred, sql))) => {
                // Normalize SQL for comparison (strips type preambles and normalizes whitespace)
                let expected_normalized = normalize_sql_for_comparison(&expected_sql);
                let got_normalized = normalize_sql_for_comparison(&sql);

                if got_normalized == expected_normalized {
                    matched += 1;
                    if is_known_fail {
                        eprintln!("[{} FIXED] {} - known failure now passes!", engine, stem);
                    }
                } else if is_known_fail {
                    // Expected failure - don't count as mismatched
                    eprintln!("[{} KNOWN] {} - expected failure (skipped)", engine, stem);
                } else {
                    mismatched.push(stem.to_string());
                    // Print diff for debugging
                    eprintln!("\n[{} MISMATCH] {}", engine, stem);
                    eprintln!("--- Expected (first 500 chars) ---");
                    eprintln!("{}", &expected_normalized[..expected_normalized.len().min(500)]);
                    eprintln!("--- Got (first 500 chars) ---");
                    eprintln!("{}", &got_normalized[..got_normalized.len().min(500)]);
                }
            }
            Ok(Err(e)) => {
                let msg = e
                    .downcast_ref::<String>()
                    .map(|s| s.as_str())
                    .or_else(|| e.downcast_ref::<&str>().copied())
                    .unwrap_or("unknown panic");
                if is_known_fail {
                    eprintln!("[{} KNOWN] {} - expected error (skipped)", engine, stem);
                } else {
                    eprintln!(
                        "[{} ERROR] {} — {}",
                        engine,
                        stem,
                        &msg[..msg.len().min(200)]
                    );
                    errored.push(stem.to_string());
                }
            }
            Err(_) => {
                if is_known_fail {
                    eprintln!("[{} KNOWN] {} - expected timeout (skipped)", engine, stem);
                } else {
                    eprintln!("[{} TIMEOUT] {}", engine, stem);
                    timed_out.push(stem.to_string());
                }
            }
        }
    }

    eprintln!(
        "\n[{}] {}/{} matched, {} mismatched, {} errors, {} timeouts, {} missing SQL",
        engine,
        matched,
        total,
        mismatched.len(),
        errored.len(),
        timed_out.len(),
        missing_sql.len()
    );

    if !mismatched.is_empty() {
        eprintln!("[{}] mismatched: {:?}", engine, mismatched);
    }
    if !errored.is_empty() {
        eprintln!("[{}] errors: {:?}", engine, errored);
    }
    if !timed_out.is_empty() {
        eprintln!("[{}] timeouts: {:?}", engine, timed_out);
    }
    if !missing_sql.is_empty() {
        eprintln!("[{}] missing SQL files: {:?}", engine, missing_sql);
    }

    // Report results but don't fail yet - we want to see all issues first
    let failed = mismatched.len() + errored.len() + timed_out.len();
    if failed > 0 {
        panic!(
            "[{}] {}/{} tests failed ({} mismatched, {} errors, {} timeouts)",
            engine,
            failed,
            total,
            mismatched.len(),
            errored.len(),
            timed_out.len()
        );
    }

    assert!(
        total >= 25,
        "[{}] Expected at least 25 tests, found {}",
        engine,
        total
    );
}

/// Run compiler fail tests for a specific engine.
/// These tests should fail compilation - success is a test failure.
fn run_compiler_fail_tests(engine: &str) {
    let dir = compiler_tests_dir().join(engine);

    if !dir.exists() {
        return; // No fail tests for this engine
    }

    let stems = fixture_stems(&dir, true);

    if stems.is_empty() {
        return;
    }

    let mut correctly_failed = 0;
    let mut incorrectly_passed = Vec::new();
    let mut total = 0;

    for stem in &stems {
        let stem = stem.as_str();

        total += 1;
        let source = std::fs::read_to_string(fixture_source(&dir, stem)).unwrap();

        // Strip existing engine annotation and add the correct one
        let clean = strip_engine(&source);
        let full_source = format!("@Engine(\"{}\");\n{}", engine, clean);

        let full_source_clone = full_source.clone();
        let roots = import_roots();
        let (tx, rx) = mpsc::channel();

        let _handle = std::thread::Builder::new()
            .stack_size(512 * 1024 * 1024)
            .spawn(move || {
                let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    let parsed =
                        parse_file(&full_source_clone, None, &roots).expect("parse failed");
                    let pred = last_predicate(&parsed).unwrap_or("Test".to_string());
                    let program = LogicaProgram::new(&parsed, HashMap::new(), HashMap::new())
                        .expect("program creation failed");
                    let _sql = program
                        .formatted_predicate_sql(&pred)
                        .expect("SQL compilation failed");
                }));
                let _ = tx.send(result);
            })
            .unwrap();

        match rx.recv_timeout(Duration::from_secs(10)) {
            Ok(Ok(())) => {
                // Compilation succeeded - this is a test FAILURE
                incorrectly_passed.push(stem.to_string());
            }
            Ok(Err(_)) | Err(_) => {
                // Compilation failed or timed out - this is expected
                correctly_failed += 1;
            }
        }
    }

    eprintln!(
        "\n[{}/fail] {}/{} correctly failed, {} incorrectly passed",
        engine,
        correctly_failed,
        total,
        incorrectly_passed.len()
    );

    if !incorrectly_passed.is_empty() {
        eprintln!("[{}/fail] incorrectly passed: {:?}", engine, incorrectly_passed);
        panic!(
            "[{}/fail] {} tests should have failed but passed",
            engine,
            incorrectly_passed.len()
        );
    }
}

#[test]
fn compiler_feature_tests_sqlite() {
    run_compiler_feature_tests("sqlite");
}

#[test]
fn compiler_fail_tests_sqlite() {
    run_compiler_fail_tests("sqlite");
}

#[test]
fn compiler_feature_tests_duckdb() {
    run_compiler_feature_tests("duckdb");
}

#[test]
fn compiler_fail_tests_duckdb() {
    run_compiler_fail_tests("duckdb");
}

#[test]
fn compiler_feature_tests_psql() {
    run_compiler_feature_tests("psql");
}

#[test]
fn compiler_fail_tests_psql() {
    run_compiler_fail_tests("psql");
}

#[test]
fn compiler_feature_tests_bigquery() {
    run_compiler_feature_tests("bigquery");
}

#[test]
fn compiler_fail_tests_bigquery() {
    run_compiler_fail_tests("bigquery");
}

#[test]
fn compiler_feature_tests_trino() {
    run_compiler_feature_tests("trino");
}

#[test]
fn compiler_fail_tests_trino() {
    run_compiler_fail_tests("trino");
}

#[test]
fn compiler_feature_tests_presto() {
    run_compiler_feature_tests("presto");
}

#[test]
fn compiler_fail_tests_presto() {
    run_compiler_fail_tests("presto");
}

#[test]
fn compiler_feature_tests_databricks() {
    run_compiler_feature_tests("databricks");
}

#[test]
fn compiler_fail_tests_databricks() {
    run_compiler_fail_tests("databricks");
}
