//! Parser feature tests: comprehensive Logica parsing coverage.
//!
//! These tests verify the Rust parser against expected JSON generated by
//! Python Logica's parser. Each .l file in parser_tests/fixtures/ has a
//! corresponding .json file.
//!
//! Parsing is engine-independent (the `@Engine` annotation is just another
//! parsed annotation), so there is a single canonical fixture set.

mod common;

use std::path::PathBuf;

use synalog::parser::parse_file;

use common::normalize_json;

/// Path to the parser fixtures directory.
fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/parser_tests/fixtures")
}

/// Path to the compiler_tests directory (for import roots).
fn compiler_tests_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/compiler_tests")
}

/// Import roots for resolving imports.
fn import_roots() -> Vec<String> {
    vec![compiler_tests_dir().to_str().unwrap().to_string()]
}

#[test]
fn parser_feature_tests() {
    let dir = fixtures_dir();

    if !dir.exists() {
        panic!("parser_tests/fixtures/ directory not found");
    }

    let mut entries: Vec<_> = std::fs::read_dir(&dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.file_name()
                .to_str()
                .map(|s| s.ends_with(".l"))
                .unwrap_or(false)
        })
        .collect();
    entries.sort_by_key(|e| e.file_name());

    let mut matched = 0;
    let mut mismatched = Vec::new();
    let mut errored = Vec::new();
    let mut missing_json = Vec::new();
    let mut total = 0;

    for entry in &entries {
        let l_name = entry.file_name();
        let l_name = l_name.to_str().unwrap();
        let stem = &l_name[..l_name.len() - 2]; // remove ".l"

        let json_path = dir.join(format!("{}.json", stem));
        if !json_path.exists() {
            missing_json.push(stem.to_string());
            continue;
        }

        total += 1;
        let source = std::fs::read_to_string(entry.path()).unwrap();
        let expected_json = std::fs::read_to_string(&json_path).unwrap();
        let roots = import_roots();

        match parse_file(&source, None, &roots) {
            Ok(result) => {
                let rust_json = result.to_string_fmt(false);
                let norm_rust = normalize_json(&rust_json);
                let norm_expected = normalize_json(&expected_json);

                if norm_rust == norm_expected {
                    matched += 1;
                } else {
                    mismatched.push(stem.to_string());
                    // Print diff for debugging
                    if std::env::var("SHOW_DIFFS").is_ok() {
                        eprintln!("\n[MISMATCH] {}", stem);
                        eprintln!("--- Expected (first 500 chars) ---");
                        eprintln!("{}", &norm_expected[..norm_expected.len().min(500)]);
                        eprintln!("--- Got (first 500 chars) ---");
                        eprintln!("{}", &norm_rust[..norm_rust.len().min(500)]);
                    }
                }
            }
            Err(e) => {
                eprintln!("[ERROR] {} — {}", stem, &e.message[..e.message.len().min(100)]);
                errored.push(stem.to_string());
            }
        }
    }

    eprintln!(
        "\n[parser] {}/{} matched, {} mismatched, {} errors, {} missing JSON",
        matched,
        total,
        mismatched.len(),
        errored.len(),
        missing_json.len()
    );

    if !mismatched.is_empty() {
        eprintln!("[parser] mismatched: {:?}", mismatched);
    }
    if !errored.is_empty() {
        eprintln!("[parser] errors: {:?}", errored);
    }
    if !missing_json.is_empty() {
        eprintln!("[parser] missing JSON files: {:?}", missing_json);
    }

    let failed = mismatched.len() + errored.len();
    assert!(
        failed == 0,
        "[parser] {}/{} tests failed ({} mismatched, {} errors)",
        failed,
        total,
        mismatched.len(),
        errored.len()
    );

    assert!(total >= 25, "[parser] Expected at least 25 tests, found {}", total);
}
