SELECT
  SUM(1) AS n
FROM
  (SELECT CAST(current_timestamp AT TIME ZONE 'UTC' AS TIMESTAMP) AS timestamp) AS Now
WHERE
  (CAST(SUBSTR(CAST(Now.timestamp AS VARCHAR), 12, 2) AS BIGINT) >= 0) AND
  (CAST(SUBSTR(CAST(Now.timestamp AS VARCHAR), 12, 2) AS BIGINT) <= 23);
