SELECT
  (CASE WHEN CAST('1' AS BIGINT) < 0 THEN NULL ELSE ELEMENT_AT(ARRAY[10, 20, 30], CAST('1' AS BIGINT) + 1) END) AS e,
  (CASE WHEN CAST(1.0E0 AS BIGINT) < 0 THEN NULL ELSE ELEMENT_AT(ARRAY['a', 'b'], CAST(1.0E0 AS BIGINT) + 1) END) AS f,
  (CASE WHEN CAST(5 AS BIGINT) < 0 THEN NULL ELSE ELEMENT_AT(ARRAY[1], CAST(5 AS BIGINT) + 1) END) AS g;