SELECT
  CAST(ROUND(((5) / NULLIF(2, 0))) AS BIGINT) AS a,
  CAST(ROUND(- ((5) / NULLIF(2, 0))) AS BIGINT) AS b,
  CAST(ROUND(3.7E0) AS BIGINT) AS c,
  CAST(ROUND(((9) / NULLIF(4, 0))) AS BIGINT) AS d;