WITH t_0_V AS (SELECT * FROM VALUES
  (1),
  (2)
AS UNUSED_TABLE_NAME(k))
SELECT
  V.k AS k,
  ARRAY_JOIN(CASE WHEN (V.k = 1) THEN ARRAY() ELSE ARRAY("a", "b") END, ",") AS s
FROM
  t_0_V AS V ORDER BY k NULLS LAST;