WITH t_8_V AS (SELECT * FROM VALUES
  (3, "b"),
  (1, "c"),
  (2, "a")
AS UNUSED_TABLE_NAME(k, n)),
t_5_L AS (SELECT
  (CASE WHEN COUNT(*) = 0 THEN NULL ELSE TRANSFORM(ARRAY_SORT(COLLECT_LIST(STRUCT(V.k AS arg, STRUCT(V.n AS n) AS value))), s -> s.value) END) AS l
FROM
  t_8_V AS V),
t_0_J AS (SELECT
  (CASE WHEN COUNT(*) = 0 THEN NULL ELSE TRANSFORM(ARRAY_SORT(COLLECT_LIST(STRUCT(x_12 AS arg, (CASE WHEN x_12 < 0 THEN NULL ELSE ELEMENT_AT(t_4_L.l, CAST(x_12 AS INT) + 1) END).n AS value))), s -> s.value) END) AS s
FROM
  t_5_L AS t_4_L, LATERAL (SELECT explode(FILTER(SEQUENCE(0, CAST(ARRAY_SIZE(t_4_L.l) AS BIGINT)), x -> x < ARRAY_SIZE(t_4_L.l))) AS x_12) AS pushkin)
SELECT
  ARRAY_JOIN(J.s, "-") AS s
FROM
  t_0_J AS J;