WITH t_4_V AS (SELECT * FROM VALUES
  ("b"),
  ("a"),
  ("B")
AS UNUSED_TABLE_NAME(w)),
t_1_L AS (SELECT
  (CASE WHEN COUNT(*) = 0 THEN NULL ELSE TRANSFORM(ARRAY_SORT(COLLECT_LIST(STRUCT(V.w AS arg, V.w AS value))), s -> s.value) END) AS l
FROM
  t_4_V AS V)
SELECT
  ARRAY_JOIN(t_0_L.l, ",") AS s
FROM
  t_1_L AS t_0_L;