WITH t_2_V AS (SELECT * FROM VALUES
  (1),
  (1),
  (2)
AS UNUSED_TABLE_NAME(x)),
t_1_L AS (SELECT
  (CASE WHEN COUNT(*) = 0 THEN NULL ELSE ARRAY_DISTINCT(TRANSFORM(COLLECT_LIST(STRUCT(V.x AS v)), s -> s.v)) END) AS l
FROM
  t_2_V AS V)
SELECT
  ARRAY_SIZE(t_0_L.l) AS n
FROM
  t_1_L AS t_0_L;