WITH t_4_V AS (SELECT * FROM VALUES
  (2, "a"),
  (1, "b")
AS UNUSED_TABLE_NAME(k, n)),
t_1_L AS (SELECT
  (CASE WHEN COUNT(*) = 0 THEN NULL ELSE TRANSFORM(ARRAY_SORT(COLLECT_LIST(STRUCT(V.k AS arg, STRUCT(V.n AS n) AS value))), s -> s.value) END) AS l
FROM
  t_4_V AS V)
SELECT
  (CASE WHEN 0 < 0 THEN NULL ELSE ELEMENT_AT(t_0_L.l, CAST(0 AS INT) + 1) END).n AS n
FROM
  t_1_L AS t_0_L;