WITH t_1_V AS (SELECT * FROM VALUES
  (1, ARRAY(1, 2)),
  (2, ARRAY(3)),
  (3, CAST(null AS ARRAY<DOUBLE>))
AS UNUSED_TABLE_NAME(k, v))
SELECT
  t_0_V.k AS k,
  ARRAY_SIZE(t_0_V.v) AS r
FROM
  t_1_V AS t_0_V ORDER BY k NULLS LAST;