SELECT
  (CASE WHEN CAST(ROUND("1") AS BIGINT) < 0 THEN NULL ELSE ELEMENT_AT(ARRAY(10, 20, 30), CAST(CAST(ROUND("1") AS BIGINT) AS INT) + 1) END) AS e,
  (CASE WHEN CAST(ROUND(1.0E0) AS BIGINT) < 0 THEN NULL ELSE ELEMENT_AT(ARRAY("a", "b"), CAST(CAST(ROUND(1.0E0) AS BIGINT) AS INT) + 1) END) AS f,
  (CASE WHEN CAST(ROUND(5) AS BIGINT) < 0 THEN NULL ELSE ELEMENT_AT(ARRAY(1), CAST(CAST(ROUND(5) AS BIGINT) AS INT) + 1) END) AS g;