WITH t_1_L AS (SELECT * FROM VALUES
  (1, ARRAY(1, 2, 3)),
  (2, ARRAY()),
  (3, ARRAY(7)),
  (4, ARRAY(5, 5, 9, 1))
AS UNUSED_TABLE_NAME(k, l))
SELECT
  t_0_L.k AS k,
  ARRAY_SIZE(CONCAT(t_0_L.l, ARRAY(0))) AS n
FROM
  t_1_L AS t_0_L ORDER BY k NULLS LAST;