WITH t_1_L AS (SELECT * FROM VALUES
  (1, ARRAY(1, 2, 3)),
  (2, ARRAY()),
  (3, ARRAY(7)),
  (4, ARRAY(5, 5, 9, 1))
AS UNUSED_TABLE_NAME(k, l))
SELECT
  t_0_L.k AS k,
  x_4 AS i
FROM
  t_1_L AS t_0_L, LATERAL (SELECT explode(FILTER(SEQUENCE(0, CAST(ARRAY_SIZE(t_0_L.l) AS BIGINT)), x -> x < ARRAY_SIZE(t_0_L.l))) AS x_4) AS pushkin ORDER BY k NULLS LAST, i NULLS LAST;