WITH t_1_L AS (SELECT * FROM VALUES
  (1, ARRAY(1, 2, 3)),
  (2, ARRAY()),
  (3, ARRAY(7)),
  (4, ARRAY(5, 5, 9, 1))
AS UNUSED_TABLE_NAME(k, l))
SELECT
  t_0_L.k AS k,
  (CASE WHEN ((ARRAY_SIZE(t_0_L.l)) - (1)) < 0 THEN NULL ELSE ELEMENT_AT(t_0_L.l, CAST(((ARRAY_SIZE(t_0_L.l)) - (1)) AS INT) + 1) END) AS v
FROM
  t_1_L AS t_0_L ORDER BY k NULLS LAST;