WITH t_1_V AS (SELECT * FROM VALUES
  (1),
  (1),
  (2)
AS UNUSED_TABLE_NAME(x)),
t_0_C AS (SELECT
  (CASE WHEN COUNT(*) = 0 THEN NULL ELSE ARRAY_DISTINCT(TRANSFORM(COLLECT_LIST(STRUCT(V.x AS v)), s -> s.v)) END) AS l
FROM
  t_1_V AS V)
SELECT
  ARRAY_SIZE(C.l) AS n
FROM
  t_0_C AS C;