WITH t_0_Gv AS (SELECT * FROM VALUES
  (1, null),
  (2, 5)
AS UNUSED_TABLE_NAME(a, b))
SELECT
  Gv.a AS a,
  (CASE WHEN Gv.a IS NULL OR Gv.b IS NULL THEN NULL ELSE GREATEST(Gv.a, Gv.b) END) AS g,
  (CASE WHEN Gv.a IS NULL OR Gv.b IS NULL THEN NULL ELSE LEAST(Gv.a, Gv.b) END) AS l,
  (CASE WHEN Gv.a IS NULL OR 2.5E0 IS NULL OR COALESCE(Gv.b, 0) IS NULL THEN NULL ELSE GREATEST(Gv.a, 2.5E0, COALESCE(Gv.b, 0)) END) AS h
FROM
  t_0_Gv AS Gv ORDER BY a NULLS LAST;