SELECT
  ARRAY_SIZE(FILTER(SEQUENCE(0, CAST(0 AS BIGINT)), x -> x < 0)) AS a,
  ARRAY_SIZE(FILTER(SEQUENCE(0, CAST(-2 AS BIGINT)), x -> x < -2)) AS b,
  ARRAY_SIZE(FILTER(SEQUENCE(0, CAST(3 AS BIGINT)), x -> x < 3)) AS c;