WITH t_0_V AS (SELECT * FROM VALUES
  (1.5E0, 42, null),
  (2.5E0, 7, 1)
AS UNUSED_TABLE_NAME(x, y, z))
SELECT
  CAST(V.x AS STRING) AS a,
  CAST(V.y AS STRING) AS b,
  CAST(V.z AS STRING) AS c
FROM
  t_0_V AS V
WHERE
  (V.x < 2);