WITH t_1_V AS (SELECT * FROM VALUES
  (1, 3, "ab"),
  (2, -4, "hello"),
  (3, 0, ""),
  (4, null, "x"),
  (5, 12, null),
  (6, 7, "seven")
AS UNUSED_TABLE_NAME(k, x, s))
SELECT
  V.k AS k
FROM
  t_1_V AS V
WHERE
  ((CASE WHEN 0 IS NULL OR (CASE WHEN V.x IS NULL OR 5 IS NULL THEN NULL ELSE LEAST(V.x, 5) END) IS NULL THEN NULL ELSE GREATEST(0, (CASE WHEN V.x IS NULL OR 5 IS NULL THEN NULL ELSE LEAST(V.x, 5) END)) END) = (CASE WHEN 0 IS NULL OR (CASE WHEN 5 IS NULL OR 5 IS NULL THEN NULL ELSE LEAST(5, 5) END) IS NULL THEN NULL ELSE GREATEST(0, (CASE WHEN 5 IS NULL OR 5 IS NULL THEN NULL ELSE LEAST(5, 5) END)) END)) ORDER BY k NULLS LAST;