WITH t_1_M AS (SELECT * FROM VALUES
  (1),
  (1),
  (2)
AS UNUSED_TABLE_NAME(k))
SELECT
  M.k AS k,
  SUM(1) AS n
FROM
  t_1_M AS M, LATERAL (SELECT explode(ARRAY(1, 2)) AS x_4) AS pushkin
WHERE
  (x_4 = M.k)
GROUP BY 1 ORDER BY k NULLS LAST;