WITH t_0_C AS (SELECT
  (CASE WHEN COUNT(*) = 0 THEN NULL ELSE TRANSFORM(COLLECT_LIST(STRUCT(x_3 AS v)), s -> s.v) END) AS l
FROM
  LATERAL (SELECT explode(ARRAY(1)) AS x_3) AS pushkin
WHERE
  (x_3 > 5))
SELECT
  COALESCE(ARRAY_SIZE(C.l), 0) AS n
FROM
  t_0_C AS C;