WITH t_0_V AS (SELECT * FROM (
  
    SELECT
      1 AS k,
      0.1 AS x
   UNION ALL
  
    SELECT
      2 AS k,
      ((1) / NULLIF(3, 0)) AS x
   UNION ALL
  
    SELECT
      3 AS k,
      ((4) / NULLIF(2, 0)) AS x
   UNION ALL
  
    SELECT
      4 AS k,
      1e6 AS x
  
) AS UNUSED_TABLE_NAME  )
SELECT
  V.k AS k,
  (SELECT (CASE WHEN synalog_v IS NULL THEN NULL WHEN ABS(synalog_v) < 0.0000000000000005 THEN '0' WHEN synalog_v = FLOOR(synalog_v) AND ABS(synalog_v) < 1e18 THEN CAST(CAST(synalog_v AS INT64) AS STRING) WHEN ABS(synalog_v) >= 1e38 THEN CAST(synalog_v AS STRING) WHEN ABS(synalog_v) < 1 THEN CAST(ROUND(CAST(CAST(synalog_v AS STRING) AS BIGNUMERIC), 15) AS STRING) ELSE CAST(ROUND(CAST(CAST(synalog_v AS STRING) AS BIGNUMERIC), 15 - LENGTH(CAST(CAST(FLOOR(ABS(CAST(CAST(synalog_v AS STRING) AS BIGNUMERIC))) AS BIGNUMERIC) AS STRING))) AS STRING) END) FROM UNNEST([V.x]) AS synalog_v) AS s
FROM
  t_0_V AS V ORDER BY k NULLS LAST;