SELECT
  (CASE WHEN CAST("1" AS INT64) < 0 THEN NULL ELSE ARRAY[10, 20, 30][SAFE_OFFSET(CAST("1" AS INT64))] END) AS e,
  (CASE WHEN CAST(1.0 AS INT64) < 0 THEN NULL ELSE ARRAY["a", "b"][SAFE_OFFSET(CAST(1.0 AS INT64))] END) AS f,
  (CASE WHEN CAST(5 AS INT64) < 0 THEN NULL ELSE ARRAY[1][SAFE_OFFSET(CAST(5 AS INT64))] END) AS g;