WITH t_0_W AS (SELECT * FROM (
  
    SELECT
      1 AS n
   UNION ALL
  
    SELECT
      22 AS n
   UNION ALL
  
    SELECT
      100 AS n
   UNION ALL
  
    SELECT
      355 AS n
   UNION ALL
  
    SELECT
      1000000 AS n
   UNION ALL
  
    SELECT
      123456789 AS n
  
) AS UNUSED_TABLE_NAME  )
SELECT
  W.n AS n,
  (SELECT (CASE WHEN synalog_v IS NULL THEN NULL WHEN ABS(synalog_v) < 0.0000000000000005 THEN '0' WHEN synalog_v = FLOOR(synalog_v) AND ABS(synalog_v) < 1e18 THEN CAST(CAST(synalog_v AS INT64) AS STRING) WHEN ABS(synalog_v) >= 1e38 THEN CAST(synalog_v AS STRING) WHEN ABS(synalog_v) < 1 THEN CAST(ROUND(CAST(CAST(synalog_v AS STRING) AS BIGNUMERIC), 15) AS STRING) ELSE CAST(ROUND(CAST(CAST(synalog_v AS STRING) AS BIGNUMERIC), 15 - LENGTH(CAST(CAST(FLOOR(ABS(CAST(CAST(synalog_v AS STRING) AS BIGNUMERIC))) AS BIGNUMERIC) AS STRING))) AS STRING) END) FROM UNNEST([((W.n) / NULLIF(7, 0))]) AS synalog_v) AS t
FROM
  t_0_W AS W ORDER BY n NULLS LAST;