SELECT
  CAST((CAST(5 AS DOUBLE) / NULLIF(2, 0)) AS BIGINT) AS a,
  CAST(- (CAST(5 AS DOUBLE) / NULLIF(2, 0)) AS BIGINT) AS b,
  CAST(3.7E0 AS BIGINT) AS c,
  CAST((CAST(9 AS DOUBLE) / NULLIF(4, 0)) AS BIGINT) AS d;